// Back Office console (/console). Staff- and admin-facing: short and direct.
export const consoleCopy = {
  backOffice: { th: 'Back Office', en: 'Back Office' },
  backToSite: { th: 'กลับหน้าเว็บ', en: 'Back to site' },
  fullscreen: { th: 'เต็มจอ', en: 'Full screen' },
  exitFullscreen: { th: 'ออกจากเต็มจอ', en: 'Exit full screen' },
  soon: { th: 'เร็วๆ นี้', en: 'Soon' },
  roleAdmin: { th: 'แอดมิน', en: 'Admin' },
  roleStaff: { th: 'พนักงาน', en: 'Staff' },

  // tabs
  tabOverview: { th: 'ภาพรวม', en: 'Overview' },
  tabDesk: { th: 'ขาย + เช็คอิน', en: 'Sell + check-in' },
  tabTime: { th: 'ลงเวลา', en: 'Time clock' },
  tabMembers: { th: 'ลูกค้า', en: 'Members' },
  tabReports: { th: 'รายงาน', en: 'Reports' },
  pendingLeave: { th: 'มีคำขอหยุดรออนุมัติ {n} รายการ', en: '{n} leave requests waiting' },
  tabCatalog: { th: 'สินค้าและราคา', en: 'Products & prices' },
  tabSettings: { th: 'ตั้งค่า', en: 'Settings' },
  tabTeam: { th: 'ทีมงานและสิทธิ์', en: 'Team & roles' },
  groupFront: { th: 'หน้าร้าน', en: 'Front desk' },
  groupBack: { th: 'หลังร้าน', en: 'Back of house' },
  groupSystem: { th: 'ระบบ', en: 'System' },

  // dashboard
  hello: { th: 'สวัสดี คุณ', en: 'Hello, ' },
  helloFallback: { th: 'สวัสดี', en: 'Hello' },
  inStoreNow: { th: 'คนในร้านตอนนี้', en: 'In the spa now' },
  seatsLeft: { th: 'ว่างอีก', en: 'Free' },
  seatsUnit: { th: 'ที่', en: 'spots' },
  checkInsToday: { th: 'เช็คอินวันนี้', en: 'Check-ins today' },
  paidCount: { th: 'จ่ายเงิน', en: 'paid' },
  freeCount: { th: 'ใช้สิทธิ์', en: 'free' },
  takingsToday: { th: 'รับเงินวันนี้', en: 'Taken today' },
  cash: { th: 'เงินสด', en: 'Cash' },
  transfer: { th: 'โอน', en: 'Transfer' },
  card: { th: 'บัตร', en: 'Card' },
  newMembersToday: { th: 'สมาชิกใหม่วันนี้', en: 'New members today' },
  membersTotal: { th: 'รวม', en: 'Total' },
  people: { th: 'คน', en: '' },
  baht: { th: '฿', en: '฿' },

  modDeskTitle: { th: 'ขาย + เช็คอิน', en: 'Sell + check-in' },
  modDeskDesc: { th: 'สแกน QR ลูกค้า รับเงิน ดูคนในร้าน', en: 'Scan members, take payment, see who’s in' },
  modDeskMeta: { th: 'คนอยู่ในร้าน', en: 'in the spa' },
  modTimeTitle: { th: 'ลงเวลาทำงาน', en: 'Time clock' },
  modTimeDesc: { th: 'เข้า-ออกงาน กะ และแก้เวลาของทีม', en: 'Clock in/out, shifts, fix the team’s times' },
  modMembersTitle: { th: 'ข้อมูลลูกค้า', en: 'Members' },
  modMembersDesc: { th: 'ค้นหาและแก้ไขข้อมูลสมาชิก', en: 'Find and edit members' },
  modMembersMeta: { th: 'สมาชิก', en: 'members' },
  modReportsTitle: { th: 'รายงาน', en: 'Reports' },
  modReportsDesc: { th: 'ยอดขาย การเข้าใช้ ลงเวลา · CSV', en: 'Sales, visits, hours · CSV' },

  hourlyHeading: { th: 'เช็คอินรายชั่วโมง', en: 'Check-ins by hour' },
  recentHeading: { th: 'เช็คอินล่าสุด', en: 'Latest check-ins' },
  seeAll: { th: 'ดูทั้งหมด', en: 'See all' },
  nobodyYet: { th: 'ยังไม่มีการเช็คอินวันนี้', en: 'No check-ins yet today' },
  inside: { th: 'ในร้าน', en: 'Inside' },
  left: { th: 'ออกแล้ว', en: 'Left' },
  free: { th: 'ใช้สิทธิ์ฟรี', en: 'Free' },
  packageVisit: { th: 'แพ็กเกจ', en: 'Package' },
  notSetUp: {
    th: 'ยังดึงข้อมูลวันนี้ไม่ได้ — ตรวจว่ารัน supabase/schema.sql ล่าสุดแล้ว',
    en: 'Couldn’t load today’s data — make sure the latest supabase/schema.sql has been run',
  },

  memberOpen: { th: 'ดูข้อมูล / ประวัติ', en: 'Details & visits' },
  membersHeading: { th: 'ข้อมูลลูกค้า', en: 'Members' },
  membersSearchFirst: { th: 'พิมพ์ชื่อ เบอร์โทร หรือเลขสมาชิก เพื่อค้นหา', en: 'Type a name, phone or member number to search' },
  membersKeepTyping: { th: 'พิมพ์อีกนิด — ชื่ออย่างน้อย 2 ตัวอักษร หรือตัวเลขอย่างน้อย 3 ตัว', en: 'Keep typing — at least 2 letters or 3 digits' },
  membersLimited: { th: 'แสดง 50 คนแรก — พิมพ์เพิ่มให้แคบลง', en: 'Showing the first 50 — type more to narrow it down' },
  membersSearchStaff: { th: 'ค้นหาชื่อ เบอร์โทร หรือเลขสมาชิก', en: 'Search name, phone or member no.' },
  clearSearch: { th: 'ล้างคำค้นหา', en: 'Clear search' },
  tabDevices: { th: 'อุปกรณ์', en: 'Devices' },

  // /tablet — pairing a counter tablet
  pairEyebrow: { th: 'ลงทะเบียนเครื่อง', en: 'Register this device' },
  pairHeading: { th: 'เครื่องนี้ยังไม่ได้ลงทะเบียน', en: 'This device isn’t registered yet' },
  pairIntro: { th: 'ให้แอดมินจับคู่เครื่องนี้จากมือถือ ไม่ต้องพิมพ์รหัสผ่านบนเครื่องนี้', en: 'An admin pairs it from their phone — no password is typed on this device.' },
  pairStep1: { th: 'แอดมินเปิด Back Office → อุปกรณ์ → เพิ่มเครื่อง บนมือถือ', en: 'On their phone, an admin opens Back Office → Devices → Add device' },
  pairStep2: { th: 'สแกน QR นี้ด้วยกล้องมือถือ หรือพิมพ์รหัส 6 หลัก', en: 'Scan this QR with the phone camera, or type the 6-digit code' },
  pairStep3: { th: 'ตั้งชื่อเครื่อง แล้วกดลงทะเบียน — หน้านี้จะเปลี่ยนเอง', en: 'Name the device and tap Register — this screen moves on by itself' },
  pairOrType: { th: 'หรือพิมพ์รหัส', en: 'or type the code' },
  pairExpiresIn: { th: 'รหัสหมดอายุใน', en: 'Code expires in' },
  pairOnce: { th: 'ใช้ได้ครั้งเดียว', en: 'single use' },
  pairExpired: { th: 'รหัสหมดอายุแล้ว', en: 'This code has expired' },
  pairNewCode: { th: 'ขอรหัสใหม่', en: 'Get a new code' },
  pairDone: { th: 'ลงทะเบียนเรียบร้อย กำลังเปิด Back Office…', en: 'Registered — opening Back Office…' },
  tabletOnlyTitle: { th: 'ใช้ได้เฉพาะบน Tablet ของร้าน', en: 'Shop tablet only' },
  tabletOnlyBody: { th: 'หน้าขาย + เช็คอินเปิดได้จาก Tablet ที่ลงทะเบียนไว้ที่เคาน์เตอร์ ถ้าจำเป็นต้องใช้มือถือ ให้แอดมินเปิดสิทธิ์ที่ Back Office › ตั้งค่า', en: 'Selling and check-in open on the registered counter tablet. If you need your phone, an admin can allow it in Back Office › Settings.' },
  tabletOnlyBack: { th: 'กลับหน้าบัญชีของฉัน', en: 'Back to my account' },
  installTitle: { th: 'ขั้นแรก: เพิ่มไอคอนบนหน้าจอโฮม', en: 'First: add the icon to the home screen' },
  installWhy: { th: 'เปิดจากไอคอนจะเต็มจอเหมือนแอป · ลงทะเบียนเครื่องหลังเปิดจากไอคอนแล้ว', en: 'It opens full screen like an app · register the device after opening it from the icon' },
  installButton: { th: 'เพิ่มไปยังหน้าจอโฮม', en: 'Add to Home Screen' },
  installClose: { th: 'ปิด', en: 'Close' },
  installIos1: { th: 'แตะปุ่มแชร์', en: 'Tap Share' },
  installIos1b: { th: 'ที่มุมขวาบนของ Safari', en: 'at the top right of Safari' },
  installIos2: { th: 'เลื่อนลงแล้วเลือก', en: 'Scroll down and choose' },
  installIos2b: { th: 'เพิ่มไปยังหน้าจอโฮม', en: 'Add to Home Screen' },
  installIos3: { th: 'กด “เพิ่ม” ที่มุมขวาบน', en: 'Tap “Add” at the top right' },
  installIos4: { th: 'ปิด Safari แล้วเปิดจากไอคอน RAVENTA บนหน้าจอโฮม', en: 'Close Safari and open the RAVENTA icon on the home screen' },
  installUseSafari: { th: 'เบราว์เซอร์นี้บน iPad เพิ่มไอคอนไม่ได้ — เปิดลิงก์นี้ใน Safari แล้วกดปุ่มนี้อีกครั้ง', en: 'This browser on iPad can’t add the icon — open this link in Safari and tap the button again' },
  installCopy: { th: 'คัดลอกลิงก์', en: 'Copy link' },
  installCopied: { th: 'คัดลอกแล้ว — วางใน Safari', en: 'Copied — paste it in Safari' },
  installNote: { th: 'ไอคอนที่เพิ่มใหม่ต้องลงทะเบียนเครื่องอีกครั้ง (iPad เก็บข้อมูลไอคอนแยกจากเบราว์เซอร์)', en: 'A newly added icon needs registering again (iPad keeps the icon’s data apart from the browser)' },
  pairFooter: { th: 'เครื่องที่ยังไม่ลงทะเบียนเปิดระบบหลังร้านไม่ได้', en: 'Unregistered devices can’t open the back office' },
  pairBusy: { th: 'มีการขอรหัสมากเกินไป ลองใหม่อีกครั้งในอีกสักครู่', en: 'Too many codes requested — try again shortly' },
  pairNotSetUp: { th: 'ระบบลงทะเบียนเครื่องยังไม่พร้อม — แอดมินต้องรัน supabase/schema.sql ล่าสุดก่อน', en: 'Device registration isn’t set up yet — an admin needs to run the latest supabase/schema.sql' },
  pairFailed: { th: 'ขอรหัสไม่สำเร็จ ลองใหม่อีกครั้ง', en: 'Couldn’t get a code — try again' },

  // lock screen (registered tablet, nobody signed in)
  lockRegistered: { th: 'เครื่องนี้ลงทะเบียนแล้ว', en: 'This device is registered' },
  lockHeading: { th: 'สแกนบัตรสมาชิกของคุณเพื่อเริ่มใช้งาน', en: 'Scan your member card to start' },
  lockHint: { th: 'เปิดบัตรในเว็บ RAVENTA บนมือถือ แตะบัตรให้ขึ้น QR แล้วยื่นให้กล้อง', en: 'Open your card in the RAVENTA site on your phone, tap it for the QR, and hold it to the camera' },
  lockSignIn: { th: 'ลืมมือถือ? เข้าสู่ระบบด้วยรหัสผ่าน', en: 'No phone? Sign in with a password' },
  lockChecking: { th: 'กำลังตรวจสอบบัตร…', en: 'Checking card…' },
  lockWelcome: { th: 'ยืนยันแล้ว กำลังเปิด…', en: 'Verified — opening…' },
  lockButton: { th: 'ล็อก / เปลี่ยนคน', en: 'Lock / switch' },
  // Lock screen v0.21: two buttons
  lkClock: { th: 'ลงเวลา', en: 'Clock in / out' },
  lkClockSub: { th: 'เข้างาน / ออกงาน · ไม่เปิดเครื่อง', en: 'Start or end your shift · tablet stays locked' },
  lkOpen: { th: 'เปิดระบบ', en: 'Open system' },
  lkOpenSub: { th: 'ขาย · เช็คอิน · ดูลูกค้า', en: 'Sell · check in · members' },
  lkFoot: { th: 'ทั้งสองปุ่มใช้ QR บัตรสมาชิกของคุณ · กล้องเปิดเมื่อกดปุ่มเท่านั้น', en: 'Both use your member card QR · the camera turns on only when you tap' },
  lkToday: { th: 'ทำงานอยู่', en: 'On shift' },
  lkClockTitle: { th: 'ลงเวลา — สแกนบัตรของคุณ', en: 'Clock in/out — scan your card' },
  lkClockHint: { th: 'เข้างานหรือออกงาน ระบบดูให้เอง · ไม่เปิดเครื่อง', en: 'In or out is worked out for you · the tablet stays locked' },
  lkOpenTitle: { th: 'เปิดระบบ — สแกนบัตรของคุณ', en: 'Open system — scan your card' },
  lkOpenHint: { th: 'เปิดใช้งานเป็นชื่อคุณ · ยังไม่ได้ลงเวลา ระบบลงเข้างานให้', en: 'Opens under your name · clocks you in if you haven’t yet' },
  lkBack: { th: 'ยกเลิก กลับหน้าล็อก', en: 'Cancel' },
  lkIdleHint: { th: 'ไม่มีคนสแกน 60 วินาที → กลับหน้าล็อกและปิดกล้องเอง', en: 'Nobody scans for 60 s → back to the lock screen, camera off' },
  lkInTitle: { th: 'เข้างานแล้ว', en: 'Clocked in' },
  lkOutAsk: { th: 'ออกงานใช่ไหม?', en: 'Clock out?' },
  lkOutTitle: { th: 'ออกงานแล้ว', en: 'Clocked out' },
  lkJustIn: { th: 'เพิ่งเข้างานไปเมื่อ', en: 'You clocked in at' },
  lkJustInHint: { th: 'ถ้าจะออกงานจริง สแกนอีกครั้งหลัง 5 นาที หรือกดออกงานด้านล่าง', en: 'To really clock out, scan again after 5 minutes or tap below' },
  lkShift: { th: 'กะ', en: 'Shift' },
  lkNoShift: { th: 'ไม่ได้จัดกะวันนี้', en: 'No shift planned today' },
  lkStatus: { th: 'สถานะ', en: 'Status' },
  lkOnTime: { th: 'ตรงเวลา', en: 'On time' },
  lkLate: { th: 'สาย {m} นาที', en: '{m} min late' },
  lkClockedInAt: { th: 'เข้างาน', en: 'Clocked in' },
  lkWorked: { th: 'ทำงานไปแล้ว', en: 'Worked so far' },
  lkToday2: { th: 'วันนี้', en: 'Today' },
  lkPaidNote: { th: 'เวลาที่นับ (หักพักตามกะ)', en: 'Counted (after the shift break)' },
  lkOt: { th: 'OT', en: 'OT' },
  lkConfirmOut: { th: 'ยืนยันออกงาน', en: 'Clock out' },
  lkCancel: { th: 'ยกเลิก', en: 'Cancel' },
  lkBackIn: { th: 'กลับหน้าล็อกใน {s} วินาที…', en: 'Back to the lock screen in {s}…' },
  lkHm: { th: '{h} ชม. {m} นาที', en: '{h} h {m} min' },
  lkRefresh: { th: 'รีเฟรช', en: 'Refresh' },
  updateReady: { th: 'มีเวอร์ชันใหม่ — แตะเพื่อโหลดใหม่', en: 'A new version is ready — tap to reload' },
  adminMenuTitle: { th: 'แอดมินบน Tablet', en: 'Admin on the tablet' },
  adminMenuBody: { th: 'ใช้เครื่องร่วมกับพนักงาน — แอดมินเห็นยอดขายและแก้ข้อมูลได้ จึงล็อกเองเมื่อไม่ใช้ {m} นาที', en: 'A shared tablet — admins see takings and can edit, so it locks after {m} idle minutes' },
  adminLockNow: { th: 'ล็อกเครื่องตอนนี้', en: 'Lock now' },
  adminKeepUsing: { th: 'ใช้งานต่อ', en: 'Keep using' },
  adminModeChip: { th: 'โหมดแอดมิน — ล็อกเมื่อใช้เสร็จ', en: 'Admin mode — lock when done' },
  setupHintTitle: { th: 'ลงทะเบียน Tablet เครื่องนี้', en: 'Register this tablet' },
  setupHintBody: {
    th: 'Tablet หน้าร้าน? กดที่นี่เพื่อรับรหัสจับคู่ ไม่ต้องเข้าสู่ระบบ',
    en: 'Counter tablet? Tap here for a pairing code — no sign-in needed.',
  },
  adminModeShort: { th: 'โหมดแอดมิน', en: 'Admin mode' },
  membersReadOnly: { th: 'ดูอย่างเดียว · แก้ไขข้อมูลได้เฉพาะแอดมิน', en: 'View only · only admins can edit' },
  idleWarn: { th: 'จะล็อกจออัตโนมัติใน', en: 'Locking automatically in' },
  idleStay: { th: 'ใช้งานต่อ', en: 'Keep working' },
  lockNotStaff: { th: 'บัญชีที่เข้าสู่ระบบอยู่ไม่ใช่พนักงาน', en: 'The signed-in account isn’t staff' },
  lockSignOut: { th: 'ออกจากระบบ', en: 'Sign out' },

  // devices page
  devicesHeading: { th: 'อุปกรณ์', en: 'Devices' },
  addDevice: { th: 'เพิ่มเครื่อง', en: 'Add device' },
  addDeviceIntro: { th: 'บน Tablet เปิด raventawellness.com/tablet แล้วสแกน QR บนจอ หรือพิมพ์รหัส 6 หลัก', en: 'On the tablet open raventawellness.com/tablet, then scan its QR or type the 6-digit code' },
  scanTabletQr: { th: 'สแกน QR บนจอ Tablet', en: 'Scan the tablet’s QR' },
  codeLabel: { th: 'รหัส 6 หลัก', en: '6-digit code' },
  nameLabel: { th: 'ชื่อเครื่อง', en: 'Device name' },
  defaultName: { th: 'Tablet เคาน์เตอร์ 1', en: 'Counter tablet 1' },
  register: { th: 'ลงทะเบียนเครื่อง', en: 'Register device' },
  registered: { th: 'ลงทะเบียนแล้ว:', en: 'Registered:' },
  registeredHint: { th: 'Tablet จะเปลี่ยนหน้าเองภายในไม่กี่วินาที', en: 'The tablet moves on by itself within seconds' },
  noDevices: { th: 'ยังไม่มีเครื่องที่ลงทะเบียน', en: 'No devices yet' },
  online: { th: 'ออนไลน์', en: 'Online' },
  offline: { th: 'ออฟไลน์', en: 'Offline' },
  waitingKey: { th: 'รอ Tablet รับกุญแจ', en: 'Waiting for the tablet' },
  revoked: { th: 'ยกเลิกแล้ว', en: 'Revoked' },
  lastSeen: { th: 'ใช้ล่าสุด', en: 'Last seen' },
  never: { th: 'ยังไม่เคยใช้', en: 'never' },
  addedOn: { th: 'เพิ่มเมื่อ', en: 'Added' },
  rename: { th: 'เปลี่ยนชื่อ', en: 'Rename' },
  save: { th: 'บันทึก', en: 'Save' },
  cancel: { th: 'ยกเลิก', en: 'Cancel' },
  revoke: { th: 'ยกเลิกเครื่อง', en: 'Revoke' },
  revokeConfirm: { th: 'ยืนยันยกเลิกเครื่องนี้', en: 'Confirm revoke' },
  revokeHint: { th: 'ยกเลิกแล้ว เครื่องนั้นจะกลับไปหน้า “ยังไม่ได้ลงทะเบียน” ทันที ประวัติยังเก็บไว้', en: 'A revoked tablet goes straight back to “not registered”; history is kept' },
} as const

export const lockErrors: Record<string, { th: string; en: string }> = {
  not_device: { th: 'เครื่องนี้ยังไม่ได้ลงทะเบียน', en: 'This device isn’t registered' },
  qr_expired: { th: 'QR หมดอายุแล้ว — แตะบัตรเพื่อเปิด QR ใหม่', en: 'QR expired — tap the card for a fresh one' },
  qr_invalid: { th: 'QR นี้ไม่ใช่บัตรสมาชิก RAVENTA', en: 'Not a RAVENTA member card' },
  not_staff: { th: 'บัตรนี้ไม่ใช่พนักงาน — ใช้บัตรของพนักงานเท่านั้น', en: 'This card isn’t staff — staff cards only' },
  no_email: { th: 'บัญชีนี้ยังไม่มีอีเมลเข้าสู่ระบบ — ยืนยันอีเมลในหน้าตั้งค่าบัญชีก่อน', en: 'This account has no login email yet — confirm one in account settings first' },
  admin_no_clock: { th: 'แอดมินไม่ต้องลงเวลา — กด “เปิดระบบ” แทน', en: 'Admins don’t clock in — use “Open system”' },
  failed: { th: 'เข้าใช้งานไม่สำเร็จ ลองอีกครั้ง', en: 'Couldn’t sign in — try again' },
}

export const deviceErrors: Record<string, { th: string; en: string }> = {
  bad_code: { th: 'รหัสต้องเป็นตัวเลข 6 หลัก', en: 'The code is 6 digits' },
  name_required: { th: 'กรุณาตั้งชื่อเครื่อง', en: 'Please name the device' },
  code_not_found: { th: 'ไม่พบรหัสนี้ หรือหมดอายุแล้ว — ดูรหัสล่าสุดบนจอ Tablet', en: 'Code not found or expired — check the tablet’s current code' },
  not_set_up: { th: 'ระบบอุปกรณ์ยังไม่พร้อม — รัน supabase/schema.sql ล่าสุดใน Supabase ก่อน', en: 'Devices aren’t set up — run the latest supabase/schema.sql in Supabase first' },
  not_admin: { th: 'เฉพาะแอดมินเท่านั้น', en: 'Admins only' },
  failed: { th: 'ทำรายการไม่สำเร็จ ลองอีกครั้ง', en: 'Something went wrong — try again' },
}

// Time clock (/console/time, schema.sql §16).
export const timeCopy = {
  heading: { th: 'ลงเวลาทำงาน', en: 'Time clock' },
  thisWeek: { th: 'สัปดาห์นี้', en: 'This week' },
  prevWeek: { th: 'สัปดาห์ก่อน', en: 'Previous week' },
  nextWeek: { th: 'สัปดาห์ถัดไป', en: 'Next week' },
  weekOf: { th: 'สัปดาห์', en: 'Week of' },
  csv: { th: 'ดาวน์โหลด CSV', en: 'Download CSV' },
  myStatus: { th: 'สถานะของฉัน', en: 'My status' },
  inSince: { th: 'เข้างานตั้งแต่', en: 'Clocked in at' },
  workedSoFar: { th: 'ทำงานมาแล้ว', en: 'Worked so far' },
  notIn: { th: 'ยังไม่ได้เข้างาน — สแกนบัตรที่จอล็อกเพื่อเข้างาน', en: 'Not clocked in — scan your card on the lock screen' },
  clockOut: { th: 'ออกงาน', en: 'Clock out' },
  clockOutConfirm: { th: 'ยืนยันออกงานตอนนี้', en: 'Clock out now' },
  clockOutHint: { th: 'ออกงานแล้วจอจะล็อกให้คนถัดไป · ถ้าแค่พักหรือเปลี่ยนคน ให้กด “ล็อก / เปลี่ยนคน” แทน', en: 'The tablet locks after you clock out · on a break or handing over? Use “Lock / switch” instead' },
  myWeek: { th: 'เวลาทำงานของฉันสัปดาห์นี้', en: 'My hours this week' },
  total: { th: 'รวม', en: 'Total' },
  inNow: { th: 'ทำงานอยู่ตอนนี้', en: 'Working now' },
  nobodyIn: { th: 'ยังไม่มีใครเข้างาน', en: 'Nobody clocked in' },
  forgot: { th: 'ลืมออกงาน?', en: 'Forgot to clock out?' },
  adminOutBtn: { th: 'ลงเวลาออก', en: 'Clock out' },
  adminOutTitle: { th: 'ลงเวลาออกให้ {n}', en: 'Clock {n} out' },
  adminOutTime: { th: 'เวลาออก', en: 'Out at' },
  adminOutShiftEnd: { th: 'ใส่เวลาเลิกกะให้แล้ว — แก้ได้', en: 'Set to the shift’s end — change if needed' },
  adminOutNoShift: { th: 'ไม่มีกะวันนั้น — ใส่เวลาที่ออกจริง', en: 'No shift that day — enter when they left' },
  adminOutReason: { th: 'เหตุผล', en: 'Reason' },
  reasonForgot: { th: 'ลืมกดออก', en: 'Forgot to clock out' },
  reasonLeft: { th: 'ออกแทนให้ (กลับแล้ว)', en: 'Left — clocked out for them' },
  adminOutBadge: { th: 'แอดมินลงออก', en: 'Out by admin' },
  monthReport: { th: 'ดูรายงานทั้งเดือน', en: 'Monthly report' },
  summary: { th: 'สรุปชั่วโมงทำงาน', en: 'Hours by person' },
  days: { th: 'วัน', en: 'days' },
  entries: { th: 'รายการเข้า-ออกงาน', en: 'Entries' },
  colDate: { th: 'วันที่', en: 'Date' },
  colName: { th: 'พนักงาน', en: 'Staff' },
  colIn: { th: 'เข้า', en: 'In' },
  colOut: { th: 'ออก', en: 'Out' },
  colHours: { th: 'ชั่วโมง', en: 'Hours' },
  stillIn: { th: 'ยังไม่ออก', en: 'Still in' },
  edit: { th: 'แก้เวลา', en: 'Edit' },
  edited: { th: 'แก้ไขแล้ว', en: 'Edited' },
  byAdmin: { th: 'เพิ่มโดยแอดมิน', en: 'Added by admin' },
  byPassword: { th: 'เข้าด้วยรหัสผ่าน', en: 'Password sign-in' },
  reason: { th: 'เหตุผล (จำเป็น)', en: 'Reason (required)' },
  reasonPlaceholder: { th: 'เช่น ลืมสแกนออก ออกจริง 17:05', en: 'e.g. forgot to clock out, left at 17:05' },
  save: { th: 'บันทึก', en: 'Save' },
  cancel: { th: 'ยกเลิก', en: 'Cancel' },
  add: { th: 'เพิ่มรายการที่ขาด', en: 'Add a missing entry' },
  addButton: { th: 'เพิ่มรายการ', en: 'Add entry' },
  pickStaff: { th: 'เลือกพนักงาน', en: 'Choose staff' },
  none: { th: 'ไม่มีรายการในสัปดาห์นี้', en: 'No entries this week' },
  loadError: { th: 'ดึงข้อมูลลงเวลาไม่ได้ — ตรวจว่ารัน supabase/schema.sql §16 แล้ว', en: 'Couldn’t load the time clock — make sure supabase/schema.sql §16 has been run' },
  viewEntries: { th: 'เวลาเข้า-ออก', en: 'Clock entries' },
  viewRoster: { th: 'ตารางกะ', en: 'Roster' },
  viewShifts: { th: 'ตั้งค่ากะ', en: 'Shift settings' },
  viewLeave: { th: 'คำขอหยุด', en: 'Leave requests' },
  shiftsNotReady: { th: 'ระบบกะยังไม่พร้อม — รัน supabase/schema.sql §17 ใน Supabase ก่อน', en: 'Shifts aren’t set up — run supabase/schema.sql §17 in Supabase first' },
  colShift: { th: 'กะ', en: 'Shift' },
  late: { th: 'สาย', en: 'Late' },
  early: { th: 'ออกก่อน', en: 'Left early' },
  dayOff: { th: 'วันหยุด', en: 'Day off' },
  mySchedule: { th: 'กะของฉันสัปดาห์นี้', en: 'My shifts this week' },
  rosterHint: { th: 'เลือกกะให้แต่ละคนรายวัน บันทึกทันทีที่เลือก · “—” = ยังไม่จัด', en: 'Pick a shift per person per day — saved as you choose · “—” = not planned' },
  rosterNeedShifts: { th: 'ยังไม่มีกะ — ไปที่ “ตั้งค่ากะ” เพื่อเพิ่มกะก่อน', en: 'No shifts yet — add one under “Shift settings” first' },
  planRange: { th: 'จัดกะหลายวัน', en: 'Plan a date range' },
  planRangeHint: { th: 'แตะวันเริ่ม แล้วแตะวันจบบนปฏิทิน', en: 'Tap the first day, then the last day' },
  planWho: { th: 'พนักงาน', en: 'Who' },
  planAll: { th: 'ทุกคน', en: 'Everyone' },
  planDays: { th: 'เฉพาะวัน', en: 'On' },
  planShift: { th: 'กะ', en: 'Shift' },
  planClear: { th: 'ล้าง (ไม่จัดกะ)', en: 'Clear (not planned)' },
  planOverwrite: { th: 'ทับกะที่จัดไว้แล้ว', en: 'Replace days already planned' },
  planModeReplace: { th: 'แทนที่ทั้งวัน', en: 'Replace the day' },
  planModeAdd: { th: 'เพิ่มเป็นอีกกะ (ควบ)', en: 'Add as another shift' },
  planModeEmpty: { th: 'เฉพาะวันที่ยังว่าง', en: 'Empty days only' },
  planApply: { th: 'บันทึก {d} วัน × {p} คน', en: 'Save {d} days × {p} people' },
  planSaved: { th: 'บันทึกแล้ว {n} วัน ({range})', en: 'Saved {n} days ({range})' },
  planSavedMany: { th: 'บันทึกแล้ว {n} ช่อง (วัน × คน) · {range}', en: 'Saved {n} slots (days × people) · {range}' },
  planNothing: { th: 'ไม่มีวันไหนเปลี่ยน — วันที่เลือกมีกะอยู่แล้ว (เลือก “แทนที่ทั้งวัน” หรือ “เพิ่มเป็นอีกกะ” ถ้าต้องการแก้)', en: 'Nothing changed — those days were already planned (pick “Replace” or “Add” to change them)' },
  planNextWeek: { th: 'ดูสัปดาห์ถัดไป', en: 'Next week' },
  planPickRange: { th: 'เลือกช่วงวันก่อน', en: 'Pick the dates first' },
  pickWeek: { th: 'เลือกสัปดาห์จากปฏิทิน', en: 'Pick a week' },
  copyLastWeek: { th: 'คัดลอกจากสัปดาห์ก่อน', en: 'Copy last week' },
  modeWeek: { th: 'สัปดาห์', en: 'Week' },
  modeMonth: { th: 'เดือน', en: 'Month' },
  prevMonth: { th: 'เดือนก่อน', en: 'Previous month' },
  nextMonth: { th: 'เดือนถัดไป', en: 'Next month' },
  thisMonth: { th: 'เดือนนี้', en: 'This month' },
  copyPattern: { th: 'คัดลอกรูปแบบจาก 4 สัปดาห์ก่อน', en: 'Repeat from 4 weeks earlier' },
  copyPatternHint: { th: 'เติมเฉพาะช่องที่ยังว่าง ตามวันเดียวกันของ 4 สัปดาห์ก่อน', en: 'Fills empty days only, from the same weekday 4 weeks earlier' },
  copyPatternDone: { th: 'เติมแล้ว {n} ช่อง', en: '{n} days filled' },
  print: { th: 'พิมพ์ / PDF', en: 'Print / PDF' },
  monthHint: { th: 'คลิกช่องเพื่อเลือกกะ · ลากคลุมหลายช่อง (Shift/⌘ คลิกเพิ่ม, Tablet กดค้าง) หรือคลิกชื่อ/วันที่ เพื่อตั้งทีเดียว · กรอบเส้นประ = ขอหยุดรออนุมัติ', en: 'Click a day to pick a shift · drag across many (Shift/⌘-click to add, hold on a tablet) or click a name/date to set them at once · dashed = leave waiting' },
  colWorkDays: { th: 'วันทำงาน', en: 'Days' },
  colMonthHours: { th: 'ชม.', en: 'Hours' },
  rowWorking: { th: 'เข้างาน', en: 'Working' },
  belowMin: { th: 'คนน้อยกว่า {n} คน', en: 'Fewer than {n} people' },
  clearDay: { th: 'ล้าง (ยังไม่จัด)', en: 'Clear (not planned)' },
  menuMultiHint: { th: 'ติ๊กได้มากกว่า 1 กะ (สูงสุด 3)', en: 'Tick more than one shift (up to 3)' },
  shiftsOverlap: { th: 'กะที่เลือกเวลาทับกัน', en: 'These shifts overlap in time' },
  bulkSelected: { th: 'เลือก {n} ช่อง', en: '{n} selected' },
  bulkClear: { th: 'ล้าง', en: 'Clear' },
  bulkAddMode: { th: 'เพิ่มเข้ากะเดิม', en: 'Add to the day' },
  bulkCancel: { th: 'ยกเลิกการเลือก', en: 'Cancel selection' },
  bulkDone: { th: 'บันทึกแล้ว {n} ช่อง', en: '{n} days saved' },
  selectDay: { th: 'เลือกทุกคนในวันนี้', en: 'Select everyone this day' },
  selectPerson: { th: 'เลือกทั้งเดือนของคนนี้', en: 'Select this person’s month' },
  onLeave: { th: 'ลา', en: 'Leave' },
  leaveWaiting: { th: 'ขอหยุด รออนุมัติ', en: 'Leave requested' },
  holiday: { th: 'วันหยุดนักขัตฤกษ์', en: 'Public holiday' },
  shiftCode: { th: 'ตัวย่อ', en: 'Code' },
  shiftColor: { th: 'สี', en: 'Colour' },
  ruleMinStaff: { th: 'คนขั้นต่ำต่อวัน', en: 'Minimum people a day' },
  ruleMinStaffHint: { th: 'ตารางรายเดือนเตือนวันที่คนน้อยกว่านี้ · 0 = ไม่เตือน', en: 'The monthly roster flags days below this · 0 = off' },
  shiftTemplates: { th: 'กะทำงาน', en: 'Shifts' },
  shiftTemplatesHint: { th: 'เวลาเลิกน้อยกว่าเวลาเข้า = เลิกวันถัดไป · เวลาพักไม่นับเป็นชั่วโมงทำงาน · ปิดใช้งานกะที่เลิกใช้ได้ (ประวัติยังอยู่)', en: 'An end before the start means the next day · break time is unpaid · switch off shifts you no longer use (history stays)' },
  shiftName: { th: 'ชื่อกะ', en: 'Name' },
  newShift: { th: 'เพิ่มกะใหม่', en: 'New shift' },
  shiftNamePlaceholder: { th: 'เช่น กะเช้า', en: 'e.g. Morning' },
  shiftStart: { th: 'เข้า', en: 'Start' },
  shiftEnd: { th: 'เลิก', en: 'End' },
  shiftBreak: { th: 'พัก (นาที)', en: 'Break (min)' },
  shiftActive: { th: 'ใช้งาน', en: 'In use' },
  shiftPaid: { th: 'ชั่วโมงทำงานจริง', en: 'Paid time' },
  overnight: { th: 'ข้ามคืน', en: 'overnight' },
  addShift: { th: 'เพิ่มกะ', en: 'Add shift' },
  saved: { th: 'บันทึกแล้ว', en: 'Saved' },
  rules: { th: 'กติกามาสาย / OT', en: 'Late and overtime rules' },
  ruleGrace: { th: 'มาสายได้ไม่เกิน (นาที)', en: 'Late grace (minutes)' },
  ruleGraceHint: { th: 'เข้าช้ากว่านี้นับเป็น “สาย” (นับตั้งแต่เวลาเข้ากะ)', en: 'Later than this counts as late (from the shift start)' },
  ruleOt: { th: 'นับ OT เมื่อเกินเวลาเลิกอย่างน้อย (นาที)', en: 'Count OT after (minutes past end)' },
  ruleOtHint: { th: 'อยู่เกินน้อยกว่านี้ไม่นับ OT', en: 'Staying less than this isn’t overtime' },
  hoursShort: { th: 'ชม.', en: 'h' },
  minutesShort: { th: 'น.', en: 'm' },
} as const

export const timeErrors: Record<string, { th: string; en: string }> = {
  not_signed_in: { th: 'กรุณาเข้าสู่ระบบก่อน', en: 'Please sign in first' },
  not_device: { th: 'ออกงานได้ที่ Tablet ของร้านเท่านั้น', en: 'Clock out on the shop tablet' },
  not_clocked_in: { th: 'คุณยังไม่ได้เข้างาน', en: 'You aren’t clocked in' },
  not_admin: { th: 'เฉพาะแอดมินเท่านั้น', en: 'Admins only' },
  need_reason: { th: 'กรุณาใส่เหตุผลอย่างน้อย 3 ตัวอักษร', en: 'Please give a reason (3+ characters)' },
  need_out: { th: 'กรุณาใส่เวลาออกงาน', en: 'Please enter the clock-out time' },
  bad_time: { th: 'รูปแบบเวลาไม่ถูกต้อง', en: 'That time isn’t valid' },
  out_before_in: { th: 'เวลาออกต้องหลังเวลาเข้า', en: 'Clock-out must be after clock-in' },
  in_future: { th: 'ใส่เวลาในอนาคตไม่ได้', en: 'Times can’t be in the future' },
  too_long: { th: 'รายการเดียวยาวเกิน 24 ชั่วโมงไม่ได้', en: 'An entry can’t be longer than 24 hours' },
  already_open: { th: 'พนักงานคนนี้มีรายการที่ยังไม่ออกงานอยู่แล้ว', en: 'This person already has an open entry' },
  not_staff: { th: 'คนนี้ไม่ใช่พนักงาน', en: 'This person isn’t staff' },
  not_found: { th: 'ไม่พบรายการนี้', en: 'Entry not found' },
  already_out: { th: 'คนนี้ลงเวลาออกไปแล้ว', en: 'Already clocked out' },
  failed: { th: 'ทำรายการไม่สำเร็จ ลองอีกครั้ง', en: 'Something went wrong — try again' },
}

export const shiftErrors: Record<string, { th: string; en: string }> = {
  not_admin: { th: 'เฉพาะแอดมินเท่านั้น', en: 'Admins only' },
  need_name: { th: 'กรุณาตั้งชื่อกะ', en: 'Please name the shift' },
  bad_time: { th: 'เวลาไม่ถูกต้อง', en: 'That time isn’t valid' },
  same_time: { th: 'เวลาเข้าและเลิกต้องไม่เท่ากัน', en: 'Start and end can’t be the same' },
  bad_break: { th: 'เวลาพักต้องอยู่ระหว่าง 0–240 นาที', en: 'Break must be 0–240 minutes' },
  bad_rule: { th: 'ตัวเลขไม่อยู่ในช่วงที่ใช้ได้', en: 'That number is out of range' },
  nothing_to_copy: { th: 'สัปดาห์ก่อนไม่มีกะให้คัดลอก หรือสัปดาห์นี้จัดครบแล้ว', en: 'Nothing to copy — last week is empty or this week is already planned' },
  nothing_to_copy_month: { th: 'ไม่มีอะไรให้คัดลอก — 4 สัปดาห์ก่อนไม่มีกะ หรือเดือนนี้จัดครบแล้ว', en: 'Nothing to copy — 4 weeks earlier is empty or this month is already planned' },
  bad_code: { th: 'ตัวย่อได้ไม่เกิน 3 ตัวอักษร · สีต้องเป็น #RRGGBB', en: 'Code: up to 3 letters · colour: #RRGGBB' },
  too_many_shifts: { th: 'วันหนึ่งลงได้ไม่เกิน 3 กะต่อคน', en: 'At most 3 shifts a day per person' },
  needs_multi_sql: { th: 'ยังลงหลายกะต่อวันไม่ได้ — รัน schema.sql §27 ใน Supabase ก่อน (กะเดิมไม่เปลี่ยน)', en: 'Several shifts a day need schema.sql §27 — run it first (nothing was changed)' },
  bad_range: { th: 'เลือกวันเริ่ม–วันจบ และวันในสัปดาห์อย่างน้อย 1 วัน', en: 'Pick a start and end date and at least one weekday' },
  need_staff: { th: 'เลือกพนักงานอย่างน้อย 1 คน', en: 'Pick at least one person' },
  range_too_long: { th: 'ช่วงยาวเกินไป — เลือกไม่เกิน 100 วันต่อครั้ง', en: 'Too long — up to 100 days at a time' },
  not_set_up: { th: 'ระบบกะยังไม่พร้อม — รัน supabase/schema.sql §17 ก่อน', en: 'Shifts aren’t set up — run supabase/schema.sql §17 first' },
  failed: { th: 'บันทึกไม่สำเร็จ ลองอีกครั้ง', en: 'Couldn’t save — try again' },
}

// Products & prices (/console/catalog, v0.20).
export const catalogCopy = {
  title: { th: 'สินค้าและราคา', en: 'Products & prices' },
  tabProducts: { th: 'สินค้า', en: 'Products' },
  tabHolidays: { th: 'วันหยุดนักขัตฤกษ์', en: 'Public holidays' },
  tabPromotions: { th: 'โปรโมชั่น', en: 'Promotions' },
  notSetUp: { th: 'ระบบสินค้ายังไม่พร้อม — รัน supabase/schema.sql §18 ก่อน', en: 'Products aren’t set up — run supabase/schema.sql §18 first' },

  kind_day_pass: { th: 'Day Pass', en: 'Day Pass' },
  kind_package: { th: 'แพ็กเกจ', en: 'Package' },
  kind_addon: { th: 'ส่วนเสริม', en: 'Add-on' },
  pkgPrice: { th: 'ราคา (บาท)', en: 'Price (THB)' },
  pkgHeading: { th: 'ตั้งค่าแพ็กเกจ', en: 'Package settings' },
  pkgType: { th: 'ประเภท', en: 'Type' },
  pkgCount: { th: 'เหมาจำนวนครั้ง', en: 'Set number of visits' },
  pkgUnlimited: { th: 'ไม่จำกัดครั้ง', en: 'Unlimited visits' },
  pkgVisits: { th: 'จำนวนครั้ง', en: 'Visits' },
  pkgValid: { th: 'ใช้ได้นาน', en: 'Valid for' },
  pkgDays: { th: 'วัน', en: 'days' },
  pkgMonths: { th: 'เดือน (× 30 วัน)', en: 'months (× 30 days)' },
  pkgStart: { th: 'เริ่มนับวันหมดอายุ', en: 'Starts counting' },
  pkgStartPurchase: { th: 'วันที่ซื้อ', en: 'On purchase' },
  pkgStartFirstUse: { th: 'วันที่ใช้ครั้งแรก', en: 'On first visit' },
  pkgActivate: { th: 'ต้องเริ่มใช้ภายใน (วัน)', en: 'Must start within (days)' },
  pkgDaysAllowed: { th: 'ใช้ได้วันไหน', en: 'Usable on' },
  pkgAnyDay: { th: 'ทุกวัน', en: 'Any day' },
  pkgWeekdayOnly: { th: 'เฉพาะวันธรรมดา', en: 'Weekdays only' },
  pkgStamp: { th: 'เข้าใช้ด้วยแพ็กเกจได้แสตมป์', en: 'Package visits earn a stamp' },
  pkgShare: { th: 'แชร์ให้เพื่อนสมาชิก', en: 'Sharing with friends' },
  pkgShareOff: { th: 'ไม่ให้แชร์', en: 'Off' },
  pkgShareSplit: { th: 'แบ่งทีละครั้ง', en: 'One visit per link' },
  pkgShareWhole: { th: 'ใช้ร่วมทั้งแพ็กเกจ', en: 'Whole package' },
  pkgShareSplitHint: { th: 'เจ้าของส่งลิงก์ทางอีเมลหรือให้สแกน QR · 1 ลิงก์ = แบ่งให้เพื่อน 1 ครั้ง (หักจากแพ็กเกจเจ้าของ) · ดึงคืนได้ถ้ายังไม่ใช้ · แสตมป์เฉพาะเจ้าของ', en: 'Owner sends a link by email or QR · each link hands a friend 1 visit from the owner’s package · unused visits can be taken back · stamps for the owner only' },
  pkgShareWholeHint: { th: 'สำหรับครอบครัว/คู่รัก · คนที่รับลิงก์เข้าร่วมแพ็กเกจ ทุกคนใช้จากจำนวนครั้ง (หรือบัตรรายเดือน) เดียวกัน · เจ้าของเอาออกได้ · แสตมป์เฉพาะเจ้าของ', en: 'For families and couples · whoever accepts joins the package and everyone uses the same visits (or pass) · the owner can remove them · stamps for the owner only' },
  pkgPriceNote: { th: 'แพ็กเกจมีราคาเดียว ขายได้เฉพาะลูกค้าที่เป็นสมาชิก', en: 'One price; sold to members only' },
  pkgSummaryCount: { th: '{n} ครั้ง', en: '{n} visits' },
  pkgSummaryUnlimited: { th: 'ไม่จำกัดครั้ง', en: 'Unlimited' },
  pkgSummaryDays: { th: '{n} วัน', en: '{n} days' },
  kind_merch: { th: 'สินค้า', en: 'Merchandise' },
  kind_souvenir: { th: 'ของที่ระลึก', en: 'Souvenir' },

  colName: { th: 'ชื่อ', en: 'Name' },
  colKind: { th: 'ประเภท', en: 'Type' },
  colPrice: { th: 'ราคา (ธรรมดา / ส-อา / นักขัตฤกษ์)', en: 'Price (weekday / weekend / holiday)' },
  colStock: { th: 'สต็อก', en: 'Stock' },
  colStatus: { th: 'สถานะ', en: 'Status' },
  onSale: { th: 'ขายอยู่', en: 'On sale' },
  off: { th: 'ปิดขาย', en: 'Off' },
  noStock: { th: 'ไม่นับสต็อก', en: 'Not tracked' },
  addProduct: { th: '+ เพิ่มสินค้า', en: '+ Add product' },
  edit: { th: 'แก้ไข', en: 'Edit' },
  newProduct: { th: 'สินค้าใหม่', en: 'New product' },
  nameTh: { th: 'ชื่อ (ไทย)', en: 'Name (Thai)' },
  nameEn: { th: 'ชื่อ (อังกฤษ)', en: 'Name (English)' },
  priceWeekday: { th: 'ราคาวันธรรมดา', en: 'Weekday price' },
  priceWeekend: { th: 'ราคา เสาร์-อาทิตย์', en: 'Weekend price' },
  priceHoliday: { th: 'ราคาวันหยุดนักขัตฤกษ์', en: 'Holiday price' },
  priceBlankHint: { th: 'เว้นว่าง = ใช้ราคาวันธรรมดา (นักขัตฤกษ์เว้นว่าง = ราคาเสาร์-อาทิตย์)', en: 'Blank = weekday price (holiday blank = weekend price)' },
  trackStock: { th: 'นับสต็อก (ขายเกินไม่ได้)', en: 'Track stock (can’t oversell)' },
  activeLabel: { th: 'เปิดขาย', en: 'On sale' },
  sortLabel: { th: 'ลำดับ', en: 'Order' },
  save: { th: 'บันทึก', en: 'Save' },
  cancel: { th: 'ยกเลิก', en: 'Cancel' },
  saved: { th: 'บันทึกแล้ว', en: 'Saved' },
  dayPassNote: { th: 'Day Pass มีรายการเดียว ลบหรือเปลี่ยนประเภทไม่ได้ · ราคานี้ใช้ทันทีที่หน้าเคาน์เตอร์', en: 'There is one Day Pass; it can’t be removed or retyped · prices apply at the counter at once' },

  variants: { th: 'แบบย่อย (ไซซ์ / สี)', en: 'Variants (size / colour)' },
  variantsHint: { th: 'มีแบบย่อย = พนักงานต้องเลือกแบบตอนขาย · สต็อกนับแยกแต่ละแบบ', en: 'With variants, staff pick one when selling · stock is per variant' },
  variantLabel: { th: 'แบบ เช่น ดำ / M', en: 'Label e.g. Black / M' },
  sku: { th: 'รหัส SKU', en: 'SKU' },
  addVariant: { th: '+ เพิ่มแบบ', en: '+ Add variant' },
  stock: { th: 'คงเหลือ', en: 'On hand' },
  setStock: { th: 'ปรับสต็อก', en: 'Set stock' },
  stockReason: { th: 'เหตุผล เช่น รับของเข้า / นับใหม่', en: 'Reason e.g. delivery / recount' },
  stockHint: { th: 'ใส่จำนวนที่มีจริงตอนนี้ · บันทึกชื่อผู้ปรับและเหตุผล', en: 'Enter the actual count now · your name and reason are logged' },

  holidayDate: { th: 'วันที่', en: 'Date' },
  holidayName: { th: 'ชื่อวันหยุด', en: 'Holiday name' },
  addHoliday: { th: 'เพิ่มวันหยุด', en: 'Add holiday' },
  holidayHint: { th: 'วันที่อยู่ในรายการนี้ใช้ “ราคาวันหยุดนักขัตฤกษ์” และใช้สิทธิ์ Day Pass ฟรีไม่ได้', en: 'These dates use the holiday price, and the free Day Pass can’t be used' },
  noHolidays: { th: 'ยังไม่มีวันหยุด', en: 'No holidays yet' },
  remove: { th: 'ลบ', en: 'Remove' },
  past: { th: 'ผ่านไปแล้ว', en: 'Past' },

  addPromotion: { th: '+ เพิ่มโปรโมชั่น', en: '+ Add promotion' },
  newPromotion: { th: 'โปรโมชั่นใหม่', en: 'New promotion' },
  promoName: { th: 'ชื่อโปรโมชั่น (แสดงในบิล)', en: 'Name (shown on the bill)' },
  promoKind: { th: 'ส่วนลด', en: 'Discount' },
  pct: { th: '% ลด', en: '% off' },
  thb: { th: 'บาท', en: 'THB off' },
  promoValue: { th: 'จำนวน', en: 'Amount' },
  scope: { th: 'ใช้กับ', en: 'Applies to' },
  scope_all: { th: 'ทั้งบิล', en: 'Whole bill' },
  scope_day_pass: { th: 'Day Pass', en: 'Day Pass' },
  scope_product: { th: 'สินค้าที่เลือก', en: 'One product' },
  promoCode: { th: 'โค้ด (เว้นว่าง = ลดอัตโนมัติ)', en: 'Code (blank = automatic)' },
  startsOn: { th: 'เริ่ม', en: 'From' },
  endsOn: { th: 'ถึง', en: 'Until' },
  auto: { th: 'อัตโนมัติ', en: 'Automatic' },
  always: { th: 'ไม่มีกำหนด', en: 'No end date' },
  promoHint: { th: 'บิลหนึ่งใช้ได้ 1 โปรโมชั่น: ใส่โค้ด = ใช้โปรของโค้ดนั้น · ไม่ใส่โค้ด = ระบบเลือกโปรอัตโนมัติที่ลดได้มากที่สุด', en: 'One promotion per bill: a code uses that promotion; otherwise the automatic one giving the biggest discount' },
  promoActive: { th: 'เปิดใช้', en: 'Active' },
  noPromotions: { th: 'ยังไม่มีโปรโมชั่น', en: 'No promotions yet' },
  running: { th: 'ใช้อยู่วันนี้', en: 'Running today' },
  notRunning: { th: 'ไม่อยู่ในช่วง', en: 'Not running' },
} as const

export const catalogErrors: Record<string, { th: string; en: string }> = {
  not_admin: { th: 'เฉพาะแอดมินเท่านั้น', en: 'Admins only' },
  need_name: { th: 'กรุณาใส่ชื่อ', en: 'Please enter a name' },
  bad_price: { th: 'ราคาต้องเป็นตัวเลข 0 ขึ้นไป', en: 'Prices must be 0 or more' },
  bad_kind: { th: 'ประเภทไม่ถูกต้อง (แพ็กเกจเปลี่ยนเป็นประเภทอื่นไม่ได้ และในทางกลับกัน)', en: 'Invalid type (a package can’t change type, nor become one)' },
  bad_package: { th: 'ตั้งค่าแพ็กเกจไม่ครบหรือตัวเลขไม่อยู่ในช่วง', en: 'Package settings are incomplete or out of range' },
  bad_stock: { th: 'จำนวนต้องเป็น 0 ขึ้นไป', en: 'Stock must be 0 or more' },
  need_reason: { th: 'กรุณาใส่เหตุผล', en: 'Please give a reason' },
  sku_taken: { th: 'รหัส SKU นี้ถูกใช้แล้ว', en: 'That SKU is already used' },
  bad_date: { th: 'วันที่ไม่ถูกต้อง', en: 'Invalid date' },
  bad_value: { th: 'จำนวนส่วนลดไม่ถูกต้อง (% ไม่เกิน 100)', en: 'Invalid discount (% max 100)' },
  bad_code: { th: 'โค้ดใช้ได้เฉพาะ A–Z และ 0–9 ยาว 3–20 ตัว', en: 'Codes are A–Z and 0–9, 3–20 long' },
  code_taken: { th: 'โค้ดนี้ถูกใช้แล้ว', en: 'That code is already used' },
  need_product: { th: 'เลือกสินค้าที่จะลด', en: 'Choose the product' },
  bad_dates: { th: 'วันเริ่มต้องไม่หลังวันสิ้นสุด', en: 'Start must not be after end' },
  not_set_up: { th: 'ระบบสินค้ายังไม่พร้อม — รัน supabase/schema.sql §18 ก่อน', en: 'Products aren’t set up — run supabase/schema.sql §18 first' },
  failed: { th: 'บันทึกไม่สำเร็จ ลองอีกครั้ง', en: 'Couldn’t save — try again' },
}

// Back Office › Settings (/console/settings, v0.20.3).
export const settingsCopy = {
  title: { th: 'ตั้งค่า', en: 'Settings' },
  notSetUp: { th: 'การตั้งค่ายังไม่พร้อม — รัน supabase/schema.sql (§19) ก่อน · ระหว่างนี้ใช้ค่าเริ่มต้น', en: 'Settings aren’t set up — run supabase/schema.sql (§19) · defaults apply meanwhile' },
  accessHeading: { th: 'สิทธิ์พนักงาน', en: 'Staff access' },
  deskOnPhone: { th: 'พนักงานทุกคนใช้ “ขาย + เช็คอิน” บนมือถือตัวเองได้', en: 'All staff may use Sell + check-in on their own phone' },
  deskOnPhoneHint: { th: 'ปิด (แนะนำ) = ใช้ได้เฉพาะ Tablet ที่ลงทะเบียน · ทุกบิลที่ทำนอก Tablet ถูกบันทึกไว้', en: 'Off (recommended) = registered tablet only · every bill taken off the tablet is logged' },
  membersOnTablet: { th: 'พนักงานดูรายชื่อลูกค้าบน Tablet ได้ (ดูอย่างเดียว)', en: 'Staff see the member list on the tablet (view only)' },
  lockHeading: { th: 'ล็อกอัตโนมัติบน Tablet', en: 'Tablet auto-lock' },
  staffIdle: { th: 'พนักงาน (นาที)', en: 'Staff (minutes)' },
  adminIdle: { th: 'แอดมิน (นาที)', en: 'Admin (minutes)' },
  lockHint: { th: 'ไม่มีการใช้งานตามเวลานี้ → เตือน 30 วินาที แล้วล็อก', en: 'No activity for this long → 30-second warning, then lock' },
  accountingHeading: { th: 'บัญชีและภาษี', en: 'Accounting & tax' },
  leaveHeading: { th: 'การลาของพนักงาน', en: 'Staff leave' },
  leaveNotice: { th: 'ต้องขอล่วงหน้า (วัน)', en: 'Notice (days)' },
  leaveQuota: { th: 'โควตา/ปี (วัน)', en: 'Days / year' },
  leaveHint: { th: 'ติ๊ก = พนักงานขอได้ · โควตา 0 = ไม่จำกัด · ลาป่วยไม่ต้องขอล่วงหน้า', en: 'Ticked = staff may ask · 0 = no limit · sick leave needs no notice' },
  vatRegistered: { th: 'จดทะเบียน VAT (ราคาขายรวม VAT 7% แล้ว)', en: 'VAT registered (prices include 7% VAT)' },
  vatRegisteredHint: { th: 'เปิด = หน้ารายงานแยกยอดก่อน VAT และภาษีขาย (ยอด × 7/107)', en: 'On = reports split out the pre-VAT amount and output VAT (× 7/107)' },
  save: { th: 'บันทึก', en: 'Save' },
  saved: { th: 'บันทึกแล้ว', en: 'Saved' },
  phoneHeading: { th: 'อนุญาตบางคนใช้มือถือ', en: 'Allow phone for some staff' },
  phoneHint: { th: 'เช่น หัวหน้ากะ ตอน Tablet เสีย · ไม่ต้องเปิดให้ทุกคน', en: 'e.g. a shift lead when the tablet is down · without opening it to everyone' },
  noStaff: { th: 'ยังไม่มีพนักงาน (role staff)', en: 'No staff yet (role staff)' },
  allowed: { th: 'ใช้มือถือได้', en: 'Phone allowed' },
  tabletOnly: { th: 'Tablet เท่านั้น', en: 'Tablet only' },
  allOn: { th: 'เปิดให้ทุกคนอยู่แล้ว', en: 'Already on for everyone' },
  elsewhereHeading: { th: 'การตั้งค่าอื่น', en: 'Other settings' },
  tabTeam: { th: 'พนักงานและอุปกรณ์', en: 'Staff & devices' },
  tabWork: { th: 'เวลาทำงานและการลา', en: 'Work time & leave' },
  tabShop: { th: 'ร้านและบัญชี', en: 'Shop & accounts' },
  unsaved: { th: 'มีการแก้ไขที่ยังไม่บันทึก', en: 'You have unsaved changes' },
  discard: { th: 'ยกเลิกการแก้ไข', en: 'Discard' },
  payHeading: { th: 'วันตัดรอบเงินเดือน', en: 'Pay periods' },
  payMonthly: { th: 'พนักงานรายเดือน ตัดรอบวันที่', en: 'Monthly staff: period ends on' },
  payEndOfMonth: { th: 'สิ้นเดือน', en: 'Last day of the month' },
  payDaily: { th: 'พนักงานรายวัน', en: 'Daily staff' },
  payWeekly: { th: 'รายสัปดาห์ ตัดทุกวัน', en: 'Weekly, ending every' },
  payHalf: { th: 'ครึ่งเดือน (1–15 / 16–สิ้นเดือน)', en: 'Twice a month (1–15 / 16–end)' },
  paySameAsMonthly: { th: 'ตัดรอบเดียวกับรายเดือน', en: 'Same as monthly staff' },
  payNow: { th: 'รอบนี้: {r}', en: 'This period: {r}' },
  payHint: { th: 'ใช้กับปุ่ม “รอบนี้ / รอบที่แล้ว” ในรายงานการลงเวลา · เปลี่ยนแล้วไม่กระทบข้อมูลลงเวลา', en: 'Used by “This / Last period” in the time report · changing it doesn’t touch any clock data' },
  payNotSetUp: { th: 'ตั้งวันตัดรอบได้หลังรัน supabase/schema.sql (§28) · ระหว่างนี้รายงานใช้เดือนปฏิทิน', en: 'Pay periods can be set after running supabase/schema.sql (§28) · meanwhile the report uses calendar months' },
  workLinks: { th: 'กะทำงาน · ผ่อนผันสาย · OT · ตารางกะ', en: 'Shifts · late grace · OT · roster' },
  elsewhereShifts: { th: 'กะทำงาน · ผ่อนผันสาย · OT', en: 'Shifts · late grace · OT' },
  elsewhereCatalog: { th: 'สินค้า · ราคา · วันหยุด · โปรโมชั่น', en: 'Products · prices · holidays · promotions' },
  elsewhereDevices: { th: 'Tablet ที่ลงทะเบียน', en: 'Registered tablets' },
  elsewhereLater: { th: 'เร็วๆ นี้: สิทธิพิเศษสมาชิกใหม่ · Waiver · ระยะเก็บข้อมูล · ข้อมูลร้าน', en: 'Soon: sign-up perks · waiver · data retention · shop details' },
} as const

export const settingsErrors: Record<string, { th: string; en: string }> = {
  not_admin: { th: 'เฉพาะแอดมินเท่านั้น', en: 'Admins only' },
  bad_minutes: { th: 'ใส่ 1–60 นาที', en: 'Use 1–60 minutes' },
  bad_leave: { th: 'วันล่วงหน้า 0–60 · โควตา 0–366 วัน', en: 'Notice 0–60 · allowance 0–366 days' },
  bad_pay: { th: 'วันตัดรอบไม่ถูกต้อง', en: 'That pay period isn’t valid' },
  pay_not_set_up: { th: 'บันทึกวันตัดรอบไม่ได้ — รัน supabase/schema.sql (§28) ก่อน', en: 'Can’t save pay periods — run supabase/schema.sql (§28) first' },
  not_staff: { th: 'คนนี้ไม่ใช่พนักงาน', en: 'Not a staff member' },
  not_set_up: { th: 'รัน supabase/schema.sql (§19) ก่อน', en: 'Run supabase/schema.sql (§19) first' },
  failed: { th: 'บันทึกไม่สำเร็จ ลองอีกครั้ง', en: 'Couldn’t save — try again' },
}
