// Back Office console (/console). Staff- and admin-facing: short and direct.
export const consoleCopy = {
  backOffice: { th: 'Back Office', en: 'Back Office' },
  backToSite: { th: 'กลับหน้าเว็บ', en: 'Back to site' },
  fullscreen: { th: 'เต็มจอ', en: 'Full screen' },
  exitFullscreen: { th: 'ออกจากเต็มจอ', en: 'Exit full screen' },
  soon: { th: 'เร็วๆ นี้', en: 'Soon' },
  roleAdmin: { th: 'แอดมิน', en: 'Admin' },
  roleStaff: { th: 'พนักงาน', en: 'Staff' },

  // tabs
  tabOverview: { th: 'ภาพรวม', en: 'Overview' },
  tabDesk: { th: 'ขาย + เช็คอิน', en: 'Sell + check-in' },
  tabTime: { th: 'ลงเวลา', en: 'Time clock' },
  tabMembers: { th: 'ลูกค้า', en: 'Members' },
  tabReports: { th: 'รายงาน', en: 'Reports' },
  tabCatalog: { th: 'สินค้าและราคา', en: 'Products & prices' },

  // dashboard
  hello: { th: 'สวัสดี คุณ', en: 'Hello, ' },
  helloFallback: { th: 'สวัสดี', en: 'Hello' },
  inStoreNow: { th: 'คนในร้านตอนนี้', en: 'In the spa now' },
  seatsLeft: { th: 'ว่างอีก', en: 'Free' },
  seatsUnit: { th: 'ที่', en: 'spots' },
  checkInsToday: { th: 'เช็คอินวันนี้', en: 'Check-ins today' },
  paidCount: { th: 'จ่ายเงิน', en: 'paid' },
  freeCount: { th: 'ใช้สิทธิ์', en: 'free' },
  takingsToday: { th: 'รับเงินวันนี้', en: 'Taken today' },
  cash: { th: 'เงินสด', en: 'Cash' },
  transfer: { th: 'โอน', en: 'Transfer' },
  card: { th: 'บัตร', en: 'Card' },
  newMembersToday: { th: 'สมาชิกใหม่วันนี้', en: 'New members today' },
  membersTotal: { th: 'รวม', en: 'Total' },
  people: { th: 'คน', en: '' },
  baht: { th: '฿', en: '฿' },

  modDeskTitle: { th: 'ขาย + เช็คอิน', en: 'Sell + check-in' },
  modDeskDesc: { th: 'สแกน QR ลูกค้า รับเงิน ดูคนในร้าน', en: 'Scan members, take payment, see who’s in' },
  modDeskMeta: { th: 'คนอยู่ในร้าน', en: 'in the spa' },
  modTimeTitle: { th: 'ลงเวลาทำงาน', en: 'Time clock' },
  modTimeDesc: { th: 'เข้า-ออกงาน กะ และแก้เวลาของทีม', en: 'Clock in/out, shifts, fix the team’s times' },
  modMembersTitle: { th: 'ข้อมูลลูกค้า', en: 'Members' },
  modMembersDesc: { th: 'ค้นหาและแก้ไขข้อมูลสมาชิก', en: 'Find and edit members' },
  modMembersMeta: { th: 'สมาชิก', en: 'members' },
  modReportsTitle: { th: 'รายงาน', en: 'Reports' },
  modReportsDesc: { th: 'ยอดขาย การเข้าใช้ ลงเวลา · CSV', en: 'Sales, visits, hours · CSV' },

  hourlyHeading: { th: 'เช็คอินรายชั่วโมง', en: 'Check-ins by hour' },
  recentHeading: { th: 'เช็คอินล่าสุด', en: 'Latest check-ins' },
  seeAll: { th: 'ดูทั้งหมด', en: 'See all' },
  nobodyYet: { th: 'ยังไม่มีการเช็คอินวันนี้', en: 'No check-ins yet today' },
  inside: { th: 'ในร้าน', en: 'Inside' },
  left: { th: 'ออกแล้ว', en: 'Left' },
  free: { th: 'ใช้สิทธิ์ฟรี', en: 'Free' },
  notSetUp: {
    th: 'ยังดึงข้อมูลวันนี้ไม่ได้ — ตรวจว่ารัน supabase/schema.sql ล่าสุดแล้ว',
    en: 'Couldn’t load today’s data — make sure the latest supabase/schema.sql has been run',
  },

  membersHeading: { th: 'ข้อมูลลูกค้า', en: 'Members' },
  tabDevices: { th: 'อุปกรณ์', en: 'Devices' },

  // /tablet — pairing a counter tablet
  pairEyebrow: { th: 'ลงทะเบียนเครื่อง', en: 'Register this device' },
  pairHeading: { th: 'เครื่องนี้ยังไม่ได้ลงทะเบียน', en: 'This device isn’t registered yet' },
  pairIntro: { th: 'ให้แอดมินจับคู่เครื่องนี้จากมือถือ ไม่ต้องพิมพ์รหัสผ่านบนเครื่องนี้', en: 'An admin pairs it from their phone — no password is typed on this device.' },
  pairStep1: { th: 'แอดมินเปิด Back Office → อุปกรณ์ → เพิ่มเครื่อง บนมือถือ', en: 'On their phone, an admin opens Back Office → Devices → Add device' },
  pairStep2: { th: 'สแกน QR นี้ด้วยกล้องมือถือ หรือพิมพ์รหัส 6 หลัก', en: 'Scan this QR with the phone camera, or type the 6-digit code' },
  pairStep3: { th: 'ตั้งชื่อเครื่อง แล้วกดลงทะเบียน — หน้านี้จะเปลี่ยนเอง', en: 'Name the device and tap Register — this screen moves on by itself' },
  pairOrType: { th: 'หรือพิมพ์รหัส', en: 'or type the code' },
  pairExpiresIn: { th: 'รหัสหมดอายุใน', en: 'Code expires in' },
  pairOnce: { th: 'ใช้ได้ครั้งเดียว', en: 'single use' },
  pairExpired: { th: 'รหัสหมดอายุแล้ว', en: 'This code has expired' },
  pairNewCode: { th: 'ขอรหัสใหม่', en: 'Get a new code' },
  pairDone: { th: 'ลงทะเบียนเรียบร้อย กำลังเปิด Back Office…', en: 'Registered — opening Back Office…' },
  pairFooter: { th: 'เครื่องที่ยังไม่ลงทะเบียนเปิดระบบหลังร้านไม่ได้', en: 'Unregistered devices can’t open the back office' },
  pairBusy: { th: 'มีการขอรหัสมากเกินไป ลองใหม่อีกครั้งในอีกสักครู่', en: 'Too many codes requested — try again shortly' },
  pairNotSetUp: { th: 'ระบบลงทะเบียนเครื่องยังไม่พร้อม — แอดมินต้องรัน supabase/schema.sql ล่าสุดก่อน', en: 'Device registration isn’t set up yet — an admin needs to run the latest supabase/schema.sql' },
  pairFailed: { th: 'ขอรหัสไม่สำเร็จ ลองใหม่อีกครั้ง', en: 'Couldn’t get a code — try again' },

  // lock screen (registered tablet, nobody signed in)
  lockRegistered: { th: 'เครื่องนี้ลงทะเบียนแล้ว', en: 'This device is registered' },
  lockHeading: { th: 'สแกนบัตรสมาชิกของคุณเพื่อเริ่มใช้งาน', en: 'Scan your member card to start' },
  lockHint: { th: 'เปิดบัตรในเว็บ RAVENTA บนมือถือ แตะบัตรให้ขึ้น QR แล้วยื่นให้กล้อง', en: 'Open your card in the RAVENTA site on your phone, tap it for the QR, and hold it to the camera' },
  lockSignIn: { th: 'ลืมมือถือ? เข้าสู่ระบบด้วยรหัสผ่าน', en: 'No phone? Sign in with a password' },
  lockChecking: { th: 'กำลังตรวจสอบบัตร…', en: 'Checking card…' },
  lockWelcome: { th: 'ยืนยันแล้ว กำลังเปิด…', en: 'Verified — opening…' },
  lockButton: { th: 'ล็อก / เปลี่ยนคน', en: 'Lock / switch' },
  adminModeChip: { th: 'โหมดแอดมิน — ล็อกเมื่อใช้เสร็จ', en: 'Admin mode — lock when done' },
  setupHintTitle: { th: 'ลงทะเบียน Tablet เครื่องนี้', en: 'Register this tablet' },
  setupHintBody: {
    th: 'Tablet หน้าร้าน? กดที่นี่เพื่อรับรหัสจับคู่ ไม่ต้องเข้าสู่ระบบ',
    en: 'Counter tablet? Tap here for a pairing code — no sign-in needed.',
  },
  adminModeShort: { th: 'โหมดแอดมิน', en: 'Admin mode' },
  membersReadOnly: { th: 'ดูอย่างเดียว · แก้ไขข้อมูลได้เฉพาะแอดมิน', en: 'View only · only admins can edit' },
  idleWarn: { th: 'จะล็อกจออัตโนมัติใน', en: 'Locking automatically in' },
  idleStay: { th: 'ใช้งานต่อ', en: 'Keep working' },
  lockNotStaff: { th: 'บัญชีที่เข้าสู่ระบบอยู่ไม่ใช่พนักงาน', en: 'The signed-in account isn’t staff' },
  lockSignOut: { th: 'ออกจากระบบ', en: 'Sign out' },

  // devices page
  devicesHeading: { th: 'อุปกรณ์', en: 'Devices' },
  addDevice: { th: 'เพิ่มเครื่อง', en: 'Add device' },
  addDeviceIntro: { th: 'บน Tablet เปิด raventawellness.com/tablet แล้วสแกน QR บนจอ หรือพิมพ์รหัส 6 หลัก', en: 'On the tablet open raventawellness.com/tablet, then scan its QR or type the 6-digit code' },
  scanTabletQr: { th: 'สแกน QR บนจอ Tablet', en: 'Scan the tablet’s QR' },
  codeLabel: { th: 'รหัส 6 หลัก', en: '6-digit code' },
  nameLabel: { th: 'ชื่อเครื่อง', en: 'Device name' },
  defaultName: { th: 'Tablet เคาน์เตอร์ 1', en: 'Counter tablet 1' },
  register: { th: 'ลงทะเบียนเครื่อง', en: 'Register device' },
  registered: { th: 'ลงทะเบียนแล้ว:', en: 'Registered:' },
  registeredHint: { th: 'Tablet จะเปลี่ยนหน้าเองภายในไม่กี่วินาที', en: 'The tablet moves on by itself within seconds' },
  noDevices: { th: 'ยังไม่มีเครื่องที่ลงทะเบียน', en: 'No devices yet' },
  online: { th: 'ออนไลน์', en: 'Online' },
  offline: { th: 'ออฟไลน์', en: 'Offline' },
  waitingKey: { th: 'รอ Tablet รับกุญแจ', en: 'Waiting for the tablet' },
  revoked: { th: 'ยกเลิกแล้ว', en: 'Revoked' },
  lastSeen: { th: 'ใช้ล่าสุด', en: 'Last seen' },
  never: { th: 'ยังไม่เคยใช้', en: 'never' },
  addedOn: { th: 'เพิ่มเมื่อ', en: 'Added' },
  rename: { th: 'เปลี่ยนชื่อ', en: 'Rename' },
  save: { th: 'บันทึก', en: 'Save' },
  cancel: { th: 'ยกเลิก', en: 'Cancel' },
  revoke: { th: 'ยกเลิกเครื่อง', en: 'Revoke' },
  revokeConfirm: { th: 'ยืนยันยกเลิกเครื่องนี้', en: 'Confirm revoke' },
  revokeHint: { th: 'ยกเลิกแล้ว เครื่องนั้นจะกลับไปหน้า “ยังไม่ได้ลงทะเบียน” ทันที ประวัติยังเก็บไว้', en: 'A revoked tablet goes straight back to “not registered”; history is kept' },
} as const

export const lockErrors: Record<string, { th: string; en: string }> = {
  not_device: { th: 'เครื่องนี้ยังไม่ได้ลงทะเบียน', en: 'This device isn’t registered' },
  qr_expired: { th: 'QR หมดอายุแล้ว — แตะบัตรเพื่อเปิด QR ใหม่', en: 'QR expired — tap the card for a fresh one' },
  qr_invalid: { th: 'QR นี้ไม่ใช่บัตรสมาชิก RAVENTA', en: 'Not a RAVENTA member card' },
  not_staff: { th: 'บัตรนี้ไม่ใช่พนักงาน — ใช้บัตรของพนักงานเท่านั้น', en: 'This card isn’t staff — staff cards only' },
  no_email: { th: 'บัญชีนี้ยังไม่มีอีเมลเข้าสู่ระบบ — ยืนยันอีเมลในหน้าตั้งค่าบัญชีก่อน', en: 'This account has no login email yet — confirm one in account settings first' },
  failed: { th: 'เข้าใช้งานไม่สำเร็จ ลองอีกครั้ง', en: 'Couldn’t sign in — try again' },
}

export const deviceErrors: Record<string, { th: string; en: string }> = {
  bad_code: { th: 'รหัสต้องเป็นตัวเลข 6 หลัก', en: 'The code is 6 digits' },
  name_required: { th: 'กรุณาตั้งชื่อเครื่อง', en: 'Please name the device' },
  code_not_found: { th: 'ไม่พบรหัสนี้ หรือหมดอายุแล้ว — ดูรหัสล่าสุดบนจอ Tablet', en: 'Code not found or expired — check the tablet’s current code' },
  not_set_up: { th: 'ระบบอุปกรณ์ยังไม่พร้อม — รัน supabase/schema.sql ล่าสุดใน Supabase ก่อน', en: 'Devices aren’t set up — run the latest supabase/schema.sql in Supabase first' },
  not_admin: { th: 'เฉพาะแอดมินเท่านั้น', en: 'Admins only' },
  failed: { th: 'ทำรายการไม่สำเร็จ ลองอีกครั้ง', en: 'Something went wrong — try again' },
}

// Time clock (/console/time, schema.sql §16).
export const timeCopy = {
  heading: { th: 'ลงเวลาทำงาน', en: 'Time clock' },
  thisWeek: { th: 'สัปดาห์นี้', en: 'This week' },
  prevWeek: { th: 'สัปดาห์ก่อน', en: 'Previous week' },
  nextWeek: { th: 'สัปดาห์ถัดไป', en: 'Next week' },
  weekOf: { th: 'สัปดาห์', en: 'Week of' },
  csv: { th: 'ดาวน์โหลด CSV', en: 'Download CSV' },
  myStatus: { th: 'สถานะของฉัน', en: 'My status' },
  inSince: { th: 'เข้างานตั้งแต่', en: 'Clocked in at' },
  workedSoFar: { th: 'ทำงานมาแล้ว', en: 'Worked so far' },
  notIn: { th: 'ยังไม่ได้เข้างาน — สแกนบัตรที่จอล็อกเพื่อเข้างาน', en: 'Not clocked in — scan your card on the lock screen' },
  clockOut: { th: 'ออกงาน', en: 'Clock out' },
  clockOutConfirm: { th: 'ยืนยันออกงานตอนนี้', en: 'Clock out now' },
  clockOutHint: { th: 'ออกงานแล้วจอจะล็อกให้คนถัดไป · ถ้าแค่พักหรือเปลี่ยนคน ให้กด “ล็อก / เปลี่ยนคน” แทน', en: 'The tablet locks after you clock out · on a break or handing over? Use “Lock / switch” instead' },
  myWeek: { th: 'เวลาทำงานของฉันสัปดาห์นี้', en: 'My hours this week' },
  total: { th: 'รวม', en: 'Total' },
  inNow: { th: 'ทำงานอยู่ตอนนี้', en: 'Working now' },
  nobodyIn: { th: 'ยังไม่มีใครเข้างาน', en: 'Nobody clocked in' },
  forgot: { th: 'ลืมออกงาน?', en: 'Forgot to clock out?' },
  summary: { th: 'สรุปชั่วโมงทำงาน', en: 'Hours by person' },
  days: { th: 'วัน', en: 'days' },
  entries: { th: 'รายการเข้า-ออกงาน', en: 'Entries' },
  colDate: { th: 'วันที่', en: 'Date' },
  colName: { th: 'พนักงาน', en: 'Staff' },
  colIn: { th: 'เข้า', en: 'In' },
  colOut: { th: 'ออก', en: 'Out' },
  colHours: { th: 'ชั่วโมง', en: 'Hours' },
  stillIn: { th: 'ยังไม่ออก', en: 'Still in' },
  edit: { th: 'แก้เวลา', en: 'Edit' },
  edited: { th: 'แก้ไขแล้ว', en: 'Edited' },
  byAdmin: { th: 'เพิ่มโดยแอดมิน', en: 'Added by admin' },
  byPassword: { th: 'เข้าด้วยรหัสผ่าน', en: 'Password sign-in' },
  reason: { th: 'เหตุผล (จำเป็น)', en: 'Reason (required)' },
  reasonPlaceholder: { th: 'เช่น ลืมสแกนออก ออกจริง 17:05', en: 'e.g. forgot to clock out, left at 17:05' },
  save: { th: 'บันทึก', en: 'Save' },
  cancel: { th: 'ยกเลิก', en: 'Cancel' },
  add: { th: 'เพิ่มรายการที่ขาด', en: 'Add a missing entry' },
  addButton: { th: 'เพิ่มรายการ', en: 'Add entry' },
  pickStaff: { th: 'เลือกพนักงาน', en: 'Choose staff' },
  none: { th: 'ไม่มีรายการในสัปดาห์นี้', en: 'No entries this week' },
  loadError: { th: 'ดึงข้อมูลลงเวลาไม่ได้ — ตรวจว่ารัน supabase/schema.sql §16 แล้ว', en: 'Couldn’t load the time clock — make sure supabase/schema.sql §16 has been run' },
  viewEntries: { th: 'เวลาเข้า-ออก', en: 'Clock entries' },
  viewRoster: { th: 'ตารางกะ', en: 'Roster' },
  viewShifts: { th: 'ตั้งค่ากะ', en: 'Shift settings' },
  shiftsNotReady: { th: 'ระบบกะยังไม่พร้อม — รัน supabase/schema.sql §17 ใน Supabase ก่อน', en: 'Shifts aren’t set up — run supabase/schema.sql §17 in Supabase first' },
  colShift: { th: 'กะ', en: 'Shift' },
  late: { th: 'สาย', en: 'Late' },
  early: { th: 'ออกก่อน', en: 'Left early' },
  dayOff: { th: 'วันหยุด', en: 'Day off' },
  mySchedule: { th: 'กะของฉันสัปดาห์นี้', en: 'My shifts this week' },
  rosterHint: { th: 'เลือกกะให้แต่ละคนรายวัน บันทึกทันทีที่เลือก · “—” = ยังไม่จัด', en: 'Pick a shift per person per day — saved as you choose · “—” = not planned' },
  rosterNeedShifts: { th: 'ยังไม่มีกะ — ไปที่ “ตั้งค่ากะ” เพื่อเพิ่มกะก่อน', en: 'No shifts yet — add one under “Shift settings” first' },
  copyLastWeek: { th: 'คัดลอกจากสัปดาห์ก่อน', en: 'Copy last week' },
  shiftTemplates: { th: 'กะทำงาน', en: 'Shifts' },
  shiftTemplatesHint: { th: 'เวลาเลิกน้อยกว่าเวลาเข้า = เลิกวันถัดไป · เวลาพักไม่นับเป็นชั่วโมงทำงาน · ปิดใช้งานกะที่เลิกใช้ได้ (ประวัติยังอยู่)', en: 'An end before the start means the next day · break time is unpaid · switch off shifts you no longer use (history stays)' },
  shiftName: { th: 'ชื่อกะ', en: 'Name' },
  newShift: { th: 'เพิ่มกะใหม่', en: 'New shift' },
  shiftNamePlaceholder: { th: 'เช่น กะเช้า', en: 'e.g. Morning' },
  shiftStart: { th: 'เข้า', en: 'Start' },
  shiftEnd: { th: 'เลิก', en: 'End' },
  shiftBreak: { th: 'พัก (นาที)', en: 'Break (min)' },
  shiftActive: { th: 'ใช้งาน', en: 'In use' },
  shiftPaid: { th: 'ชั่วโมงทำงานจริง', en: 'Paid time' },
  overnight: { th: 'ข้ามคืน', en: 'overnight' },
  addShift: { th: 'เพิ่มกะ', en: 'Add shift' },
  saved: { th: 'บันทึกแล้ว', en: 'Saved' },
  rules: { th: 'กติกามาสาย / OT', en: 'Late and overtime rules' },
  ruleGrace: { th: 'มาสายได้ไม่เกิน (นาที)', en: 'Late grace (minutes)' },
  ruleGraceHint: { th: 'เข้าช้ากว่านี้นับเป็น “สาย” (นับตั้งแต่เวลาเข้ากะ)', en: 'Later than this counts as late (from the shift start)' },
  ruleOt: { th: 'นับ OT เมื่อเกินเวลาเลิกอย่างน้อย (นาที)', en: 'Count OT after (minutes past end)' },
  ruleOtHint: { th: 'อยู่เกินน้อยกว่านี้ไม่นับ OT', en: 'Staying less than this isn’t overtime' },
  hoursShort: { th: 'ชม.', en: 'h' },
  minutesShort: { th: 'น.', en: 'm' },
} as const

export const timeErrors: Record<string, { th: string; en: string }> = {
  not_signed_in: { th: 'กรุณาเข้าสู่ระบบก่อน', en: 'Please sign in first' },
  not_device: { th: 'ออกงานได้ที่ Tablet ของร้านเท่านั้น', en: 'Clock out on the shop tablet' },
  not_clocked_in: { th: 'คุณยังไม่ได้เข้างาน', en: 'You aren’t clocked in' },
  not_admin: { th: 'เฉพาะแอดมินเท่านั้น', en: 'Admins only' },
  need_reason: { th: 'กรุณาใส่เหตุผลอย่างน้อย 3 ตัวอักษร', en: 'Please give a reason (3+ characters)' },
  need_out: { th: 'กรุณาใส่เวลาออกงาน', en: 'Please enter the clock-out time' },
  bad_time: { th: 'รูปแบบเวลาไม่ถูกต้อง', en: 'That time isn’t valid' },
  out_before_in: { th: 'เวลาออกต้องหลังเวลาเข้า', en: 'Clock-out must be after clock-in' },
  in_future: { th: 'ใส่เวลาในอนาคตไม่ได้', en: 'Times can’t be in the future' },
  too_long: { th: 'รายการเดียวยาวเกิน 24 ชั่วโมงไม่ได้', en: 'An entry can’t be longer than 24 hours' },
  already_open: { th: 'พนักงานคนนี้มีรายการที่ยังไม่ออกงานอยู่แล้ว', en: 'This person already has an open entry' },
  not_staff: { th: 'คนนี้ไม่ใช่พนักงาน', en: 'This person isn’t staff' },
  not_found: { th: 'ไม่พบรายการนี้', en: 'Entry not found' },
  failed: { th: 'ทำรายการไม่สำเร็จ ลองอีกครั้ง', en: 'Something went wrong — try again' },
}

export const shiftErrors: Record<string, { th: string; en: string }> = {
  not_admin: { th: 'เฉพาะแอดมินเท่านั้น', en: 'Admins only' },
  need_name: { th: 'กรุณาตั้งชื่อกะ', en: 'Please name the shift' },
  bad_time: { th: 'เวลาไม่ถูกต้อง', en: 'That time isn’t valid' },
  same_time: { th: 'เวลาเข้าและเลิกต้องไม่เท่ากัน', en: 'Start and end can’t be the same' },
  bad_break: { th: 'เวลาพักต้องอยู่ระหว่าง 0–240 นาที', en: 'Break must be 0–240 minutes' },
  bad_rule: { th: 'ตัวเลขไม่อยู่ในช่วงที่ใช้ได้', en: 'That number is out of range' },
  nothing_to_copy: { th: 'สัปดาห์ก่อนไม่มีกะให้คัดลอก หรือสัปดาห์นี้จัดครบแล้ว', en: 'Nothing to copy — last week is empty or this week is already planned' },
  not_set_up: { th: 'ระบบกะยังไม่พร้อม — รัน supabase/schema.sql §17 ก่อน', en: 'Shifts aren’t set up — run supabase/schema.sql §17 first' },
  failed: { th: 'บันทึกไม่สำเร็จ ลองอีกครั้ง', en: 'Couldn’t save — try again' },
}

// Products & prices (/console/catalog, v0.20).
export const catalogCopy = {
  title: { th: 'สินค้าและราคา', en: 'Products & prices' },
  tabProducts: { th: 'สินค้า', en: 'Products' },
  tabHolidays: { th: 'วันหยุดนักขัตฤกษ์', en: 'Public holidays' },
  tabPromotions: { th: 'โปรโมชั่น', en: 'Promotions' },
  notSetUp: { th: 'ระบบสินค้ายังไม่พร้อม — รัน supabase/schema.sql §18 ก่อน', en: 'Products aren’t set up — run supabase/schema.sql §18 first' },

  kind_day_pass: { th: 'Day Pass', en: 'Day Pass' },
  kind_addon: { th: 'ส่วนเสริม', en: 'Add-on' },
  kind_merch: { th: 'สินค้า', en: 'Merchandise' },
  kind_souvenir: { th: 'ของที่ระลึก', en: 'Souvenir' },

  colName: { th: 'ชื่อ', en: 'Name' },
  colKind: { th: 'ประเภท', en: 'Type' },
  colPrice: { th: 'ราคา (ธรรมดา / ส-อา / นักขัตฤกษ์)', en: 'Price (weekday / weekend / holiday)' },
  colStock: { th: 'สต็อก', en: 'Stock' },
  colStatus: { th: 'สถานะ', en: 'Status' },
  onSale: { th: 'ขายอยู่', en: 'On sale' },
  off: { th: 'ปิดขาย', en: 'Off' },
  noStock: { th: 'ไม่นับสต็อก', en: 'Not tracked' },
  addProduct: { th: '+ เพิ่มสินค้า', en: '+ Add product' },
  edit: { th: 'แก้ไข', en: 'Edit' },
  newProduct: { th: 'สินค้าใหม่', en: 'New product' },
  nameTh: { th: 'ชื่อ (ไทย)', en: 'Name (Thai)' },
  nameEn: { th: 'ชื่อ (อังกฤษ)', en: 'Name (English)' },
  priceWeekday: { th: 'ราคาวันธรรมดา', en: 'Weekday price' },
  priceWeekend: { th: 'ราคา เสาร์-อาทิตย์', en: 'Weekend price' },
  priceHoliday: { th: 'ราคาวันหยุดนักขัตฤกษ์', en: 'Holiday price' },
  priceBlankHint: { th: 'เว้นว่าง = ใช้ราคาวันธรรมดา (นักขัตฤกษ์เว้นว่าง = ราคาเสาร์-อาทิตย์)', en: 'Blank = weekday price (holiday blank = weekend price)' },
  trackStock: { th: 'นับสต็อก (ขายเกินไม่ได้)', en: 'Track stock (can’t oversell)' },
  activeLabel: { th: 'เปิดขาย', en: 'On sale' },
  sortLabel: { th: 'ลำดับ', en: 'Order' },
  save: { th: 'บันทึก', en: 'Save' },
  cancel: { th: 'ยกเลิก', en: 'Cancel' },
  saved: { th: 'บันทึกแล้ว', en: 'Saved' },
  dayPassNote: { th: 'Day Pass มีรายการเดียว ลบหรือเปลี่ยนประเภทไม่ได้ · ราคานี้ใช้ทันทีที่หน้าเคาน์เตอร์', en: 'There is one Day Pass; it can’t be removed or retyped · prices apply at the counter at once' },

  variants: { th: 'แบบย่อย (ไซซ์ / สี)', en: 'Variants (size / colour)' },
  variantsHint: { th: 'มีแบบย่อย = พนักงานต้องเลือกแบบตอนขาย · สต็อกนับแยกแต่ละแบบ', en: 'With variants, staff pick one when selling · stock is per variant' },
  variantLabel: { th: 'แบบ เช่น ดำ / M', en: 'Label e.g. Black / M' },
  sku: { th: 'รหัส SKU', en: 'SKU' },
  addVariant: { th: '+ เพิ่มแบบ', en: '+ Add variant' },
  stock: { th: 'คงเหลือ', en: 'On hand' },
  setStock: { th: 'ปรับสต็อก', en: 'Set stock' },
  stockReason: { th: 'เหตุผล เช่น รับของเข้า / นับใหม่', en: 'Reason e.g. delivery / recount' },
  stockHint: { th: 'ใส่จำนวนที่มีจริงตอนนี้ · บันทึกชื่อผู้ปรับและเหตุผล', en: 'Enter the actual count now · your name and reason are logged' },

  holidayDate: { th: 'วันที่', en: 'Date' },
  holidayName: { th: 'ชื่อวันหยุด', en: 'Holiday name' },
  addHoliday: { th: 'เพิ่มวันหยุด', en: 'Add holiday' },
  holidayHint: { th: 'วันที่อยู่ในรายการนี้ใช้ “ราคาวันหยุดนักขัตฤกษ์” และใช้สิทธิ์ Day Pass ฟรีไม่ได้', en: 'These dates use the holiday price, and the free Day Pass can’t be used' },
  noHolidays: { th: 'ยังไม่มีวันหยุด', en: 'No holidays yet' },
  remove: { th: 'ลบ', en: 'Remove' },
  past: { th: 'ผ่านไปแล้ว', en: 'Past' },

  addPromotion: { th: '+ เพิ่มโปรโมชั่น', en: '+ Add promotion' },
  newPromotion: { th: 'โปรโมชั่นใหม่', en: 'New promotion' },
  promoName: { th: 'ชื่อโปรโมชั่น (แสดงในบิล)', en: 'Name (shown on the bill)' },
  promoKind: { th: 'ส่วนลด', en: 'Discount' },
  pct: { th: '% ลด', en: '% off' },
  thb: { th: 'บาท', en: 'THB off' },
  promoValue: { th: 'จำนวน', en: 'Amount' },
  scope: { th: 'ใช้กับ', en: 'Applies to' },
  scope_all: { th: 'ทั้งบิล', en: 'Whole bill' },
  scope_day_pass: { th: 'Day Pass', en: 'Day Pass' },
  scope_product: { th: 'สินค้าที่เลือก', en: 'One product' },
  promoCode: { th: 'โค้ด (เว้นว่าง = ลดอัตโนมัติ)', en: 'Code (blank = automatic)' },
  startsOn: { th: 'เริ่ม', en: 'From' },
  endsOn: { th: 'ถึง', en: 'Until' },
  auto: { th: 'อัตโนมัติ', en: 'Automatic' },
  always: { th: 'ไม่มีกำหนด', en: 'No end date' },
  promoHint: { th: 'บิลหนึ่งใช้ได้ 1 โปรโมชั่น: ใส่โค้ด = ใช้โปรของโค้ดนั้น · ไม่ใส่โค้ด = ระบบเลือกโปรอัตโนมัติที่ลดได้มากที่สุด', en: 'One promotion per bill: a code uses that promotion; otherwise the automatic one giving the biggest discount' },
  promoActive: { th: 'เปิดใช้', en: 'Active' },
  noPromotions: { th: 'ยังไม่มีโปรโมชั่น', en: 'No promotions yet' },
  running: { th: 'ใช้อยู่วันนี้', en: 'Running today' },
  notRunning: { th: 'ไม่อยู่ในช่วง', en: 'Not running' },
} as const

export const catalogErrors: Record<string, { th: string; en: string }> = {
  not_admin: { th: 'เฉพาะแอดมินเท่านั้น', en: 'Admins only' },
  need_name: { th: 'กรุณาใส่ชื่อ', en: 'Please enter a name' },
  bad_price: { th: 'ราคาต้องเป็นตัวเลข 0 ขึ้นไป', en: 'Prices must be 0 or more' },
  bad_kind: { th: 'ประเภทไม่ถูกต้อง', en: 'Invalid type' },
  bad_stock: { th: 'จำนวนต้องเป็น 0 ขึ้นไป', en: 'Stock must be 0 or more' },
  need_reason: { th: 'กรุณาใส่เหตุผล', en: 'Please give a reason' },
  sku_taken: { th: 'รหัส SKU นี้ถูกใช้แล้ว', en: 'That SKU is already used' },
  bad_date: { th: 'วันที่ไม่ถูกต้อง', en: 'Invalid date' },
  bad_value: { th: 'จำนวนส่วนลดไม่ถูกต้อง (% ไม่เกิน 100)', en: 'Invalid discount (% max 100)' },
  bad_code: { th: 'โค้ดใช้ได้เฉพาะ A–Z และ 0–9 ยาว 3–20 ตัว', en: 'Codes are A–Z and 0–9, 3–20 long' },
  code_taken: { th: 'โค้ดนี้ถูกใช้แล้ว', en: 'That code is already used' },
  need_product: { th: 'เลือกสินค้าที่จะลด', en: 'Choose the product' },
  bad_dates: { th: 'วันเริ่มต้องไม่หลังวันสิ้นสุด', en: 'Start must not be after end' },
  not_set_up: { th: 'ระบบสินค้ายังไม่พร้อม — รัน supabase/schema.sql §18 ก่อน', en: 'Products aren’t set up — run supabase/schema.sql §18 first' },
  failed: { th: 'บันทึกไม่สำเร็จ ลองอีกครั้ง', en: 'Couldn’t save — try again' },
}
