type Bilingual = { th: string; en: string }

export const authCopy: Record<string, Bilingual> = {
  loginHeading: { th: 'เข้าสู่ระบบ', en: 'Log In' },
  signupHeading: { th: 'สมัครสมาชิก', en: 'Sign Up' },
  firstNameLabel: { th: 'ชื่อ', en: 'First Name' },
  lastNameLabel: { th: 'นามสกุล', en: 'Last Name' },
  phoneLabel: { th: 'เบอร์โทรศัพท์', en: 'Phone Number' },
  provinceLabel: { th: 'จังหวัดที่อยู่อาศัย', en: 'Province of Residence' },
  provincePlaceholder: { th: 'เลือกจังหวัด', en: 'Select a province' },
  nationalityLabel: { th: 'สัญชาติ', en: 'Nationality' },
  nationalityPlaceholder: { th: 'เลือกสัญชาติ', en: 'Select nationality' },
  emailLabel: { th: 'อีเมล', en: 'Email' },
  passwordLabel: { th: 'รหัสผ่าน', en: 'Password' },
  confirmPasswordLabel: { th: 'ยืนยันรหัสผ่าน', en: 'Confirm Password' },
  passwordHint: {
    th: 'อย่างน้อย 8 ตัวอักษร มีทั้งตัวอักษรและตัวเลข',
    en: 'At least 8 characters, with both letters and numbers',
  },
  passwordMismatch: { th: 'รหัสผ่านทั้งสองช่องไม่ตรงกัน', en: 'Passwords do not match' },
  loginButton: { th: 'เข้าสู่ระบบ', en: 'Log In' },
  signupButton: { th: 'สมัครสมาชิก', en: 'Create Account' },
  orContinueWith: { th: 'หรือดำเนินการต่อด้วย', en: 'Or continue with' },
  google: { th: 'ดำเนินการต่อด้วย Google', en: 'Continue with Google' },
  line: { th: 'ดำเนินการต่อด้วย LINE', en: 'Continue with LINE' },
  lineConnecting: { th: 'กำลังเข้าสู่ระบบด้วย LINE…', en: 'Signing you in with LINE…' },
  otherSignInOptions: { th: 'เข้าสู่ระบบด้วยวิธีอื่น', en: 'Other ways to sign in' },
  memberCardTapHint: { th: 'แตะบัตรเพื่อแสดง QR เช็คอิน', en: 'Tap your card to show your check-in QR' },
  memberCardOpen: { th: 'แสดง QR เช็คอินแบบเต็มจอ', en: 'Show check-in QR full screen' },
  memberCardDialog: { th: 'บัตรสมาชิก RAVENTA', en: 'RAVENTA member card' },
  memberCardClose: { th: 'ปิด', en: 'Close' },
  memberCardRefreshIn: { th: 'QR เปลี่ยนใหม่ใน', en: 'New QR in' },
  memberCardSeconds: { th: 'วินาที', en: 's' },
  memberCardBrightness: {
    th: 'เพิ่มความสว่างหน้าจอ แล้วยื่นให้กล้องแท็บเล็ตที่เคาน์เตอร์',
    en: 'Turn up your screen brightness and hold it up to the tablet at the counter',
  },
  memberCardFallback: {
    th: 'สแกนไม่ได้? บอกเลขสมาชิกกับพนักงานได้เลย',
    en: 'Can’t scan? Just tell staff your member number',
  },
  memberCardLoadFailed: {
    th: 'โหลด QR ไม่ได้ ตรวจสอบอินเทอร์เน็ต หรือบอกเลขสมาชิกกับพนักงาน',
    en: 'Couldn’t load your QR. Check your connection, or tell staff your member number.',
  },
  memberCardRetry: { th: 'ลองใหม่', en: 'Try again' },
  avatarChange: { th: 'เปลี่ยนรูปโปรไฟล์', en: 'Change photo' },
  avatarRemove: { th: 'ลบรูปที่อัปโหลด', en: 'Remove uploaded photo' },
  avatarBadFile: {
    th: 'เปิดไฟล์รูปนี้ไม่ได้ กรุณาเลือกรูป JPG หรือ PNG',
    en: 'That file couldn’t be opened. Please choose a JPG or PNG photo.',
  },
  avatarUploadFailed: { th: 'อัปโหลดรูปไม่สำเร็จ กรุณาลองใหม่อีกครั้ง', en: 'Upload failed. Please try again.' },
  mergeTitle: { th: 'อีเมลนี้มีบัญชีสมาชิกอยู่แล้ว — เป็นของคุณหรือเปล่า?', en: 'This email already has a membership — is it yours?' },
  // "Already a member?" — asked first when LINE isn't linked to a membership
  existingWelcome: { th: 'ยินดีต้อนรับสู่ RAVENTA', en: 'Welcome to RAVENTA' },
  existingAskHeading: { th: 'เคยเป็นสมาชิก RAVENTA แล้วหรือยัง?', en: 'Already a RAVENTA member?' },
  existingAskBody: {
    th: 'ถ้าเคยสมัครด้วยอีเมลหรือ Google มาก่อน เชื่อม LINE นี้เข้ากับบัญชีเดิมได้ เลขสมาชิกและแต้มสะสมยังอยู่ครบ',
    en: 'If you joined before with email or Google, link this LINE to that account — your member number and stamps stay.',
  },
  existingYes: { th: 'เคยแล้ว — เชื่อมกับบัญชีเดิม', en: 'Yes — link my existing account' },
  existingNo: { th: 'ยังไม่เคย — สมัครสมาชิกใหม่', en: 'No — join as a new member' },
  existingBack: { th: '← ย้อนกลับ', en: '← Back' },
  existingFindHeading: { th: 'หาบัญชีเดิมของคุณ', en: 'Find your existing account' },
  existingByCode: { th: 'รับรหัสทางอีเมล', en: 'Email me a code' },
  existingByPassword: { th: 'ใช้รหัสผ่าน', en: 'Use my password' },
  existingFindLabel: { th: 'อีเมลที่ใช้สมัคร', en: 'Email you joined with' },
  existingFindButton: { th: 'ค้นหาบัญชี', en: 'Find my account' },
  existingGoogleHint: {
    th: 'เคยสมัครด้วย Google? ใส่อีเมล Gmail ของคุณ แล้วรับรหัสทางอีเมล',
    en: 'Joined with Google? Enter your Gmail address and get a code by email.',
  },
  existingNotFound: {
    th: 'ไม่พบบัญชีที่ใช้อีเมลนี้ ลองตรวจอีกครั้ง หรือสมัครสมาชิกใหม่',
    en: 'No account uses that email. Check it, or join as a new member.',
  },
  existingPasswordLabel: { th: 'รหัสผ่าน', en: 'Password' },
  existingPasswordButton: { th: 'เข้าสู่ระบบและเชื่อม LINE', en: 'Sign in and link LINE' },
  existingWrongPassword: { th: 'อีเมลหรือรหัสผ่านไม่ถูกต้อง', en: 'Wrong email or password' },
  existingForgot: {
    th: 'ลืมรหัสผ่าน? ใช้ “รับรหัสทางอีเมล” แทนได้',
    en: 'Forgot it? Use “Email me a code” instead.',
  },
  mergeBody: {
    th: 'ถ้าเป็นของคุณ เชื่อม LINE นี้กับบัญชีนั้นได้เลย เราจะส่งรหัส 6 หลักไปที่อีเมลของบัญชีนั้น เลขสมาชิกและแต้มสะสมอยู่ครบ',
    en: 'If it’s yours, link this LINE to it — we’ll email a 6-digit code to that account. Your member number and stamps stay.',
  },
  mergeLinkButton: { th: 'ใช่ เชื่อม LINE กับบัญชีนี้', en: 'Yes — link LINE to this account' },
  mergeTitlePhone: { th: 'เบอร์นี้มีบัญชีสมาชิกอยู่แล้ว — เป็นของคุณหรือเปล่า?', en: 'This phone number already has a membership — is it yours?' },
  mergeUseAnotherPhone: { th: 'ไม่ใช่ แก้เบอร์โทร', en: 'No — change the phone number' },
  mergeTargetLimit: {
    th: 'มีการขอรหัสสำหรับบัญชีนี้หลายครั้งเกินไปวันนี้ กรุณาลองใหม่พรุ่งนี้ หรือติดต่อเรา',
    en: 'Too many code requests for this membership today. Please try again tomorrow or contact us.',
  },
  mergeUseAnother: { th: 'ไม่ใช่ ใช้อีเมลอื่น', en: 'No — use another email' },
  mergeCodeSent: { th: 'ส่งรหัส 6 หลักไปที่', en: 'We sent a 6-digit code to' },
  mergeCodeLabel: { th: 'รหัสยืนยัน', en: 'Verification code' },
  mergeVerifyButton: { th: 'ยืนยัน', en: 'Verify' },
  mergeResend: { th: 'ส่งรหัสอีกครั้ง', en: 'Send a new code' },
  mergeLinking: { th: 'กำลังเชื่อม LINE เข้ากับบัญชีของคุณ…', en: 'Linking LINE to your account…' },
  mergeWrongCode: { th: 'รหัสไม่ถูกต้อง กรุณาลองอีกครั้ง', en: 'That code isn’t right. Please try again.' },
  mergeExpired: { th: 'รหัสหมดอายุแล้ว กรุณากดส่งรหัสอีกครั้ง', en: 'That code has expired. Please send a new one.' },
  mergeTooMany: {
    th: 'กรอกรหัสผิดหลายครั้งเกินไป กรุณากดส่งรหัสใหม่',
    en: 'Too many wrong attempts. Please send a new code.',
  },
  mergeTooSoon: { th: 'เพิ่งส่งรหัสไป กรุณารอสักครู่แล้วลองใหม่', en: 'A code was just sent. Please wait a minute.' },
  mergeTargetHasLine: {
    th: 'บัญชีเดิมนี้เชื่อมกับ LINE อีกบัญชีไว้แล้ว กรุณาติดต่อเรา',
    en: 'That membership is already linked to a different LINE account. Please contact us.',
  },
  mergeNotFound: {
    th: 'เชื่อมกับบัญชีนี้จากที่นี่ไม่ได้ กรุณาติดต่อเรา หรือใช้อีเมลอื่น',
    en: 'We can’t link that membership from here. Please contact us or use another email.',
  },
  mergeFailed: {
    th: 'เกิดข้อผิดพลาด กรุณาลองใหม่อีกครั้ง หากยังไม่ได้ กรุณาติดต่อเรา',
    en: 'Something went wrong. Please try again, or contact us if it keeps happening.',
  },
  emailWhyHint: {
    th: 'ใช้ส่งเลขสมาชิกและข่าวสารสำคัญเกี่ยวกับบัญชีของคุณ',
    en: 'We’ll send your member number and important account updates here.',
  },
  lineLinkLabel: { th: 'บัญชี LINE', en: 'LINE Account' },
  lineLinkHint: {
    th: 'เชื่อม LINE ไว้ แล้วครั้งต่อไปกดเข้าสู่ระบบด้วย LINE ได้เลย และรับข่าวสารสมาชิกทาง LINE',
    en: 'Link LINE to sign in with it next time and get member updates on LINE.',
  },
  lineLinkButton: { th: 'เชื่อมบัญชี LINE', en: 'Link LINE Account' },
  lineLinked: { th: 'เชื่อมกับ LINE แล้ว', en: 'Linked to LINE' },
  lineLinkedSuccess: { th: 'เชื่อมบัญชี LINE เรียบร้อยแล้ว', en: 'Your LINE account is now linked.' },
  lineLinkAlreadyUsed: {
    th: 'บัญชี LINE นี้ถูกใช้สมัครสมาชิกอีกบัญชีหนึ่งอยู่แล้ว กรุณาติดต่อเราเพื่อรวมบัญชี',
    en: 'This LINE account is already used by another membership. Please contact us to merge them.',
  },
  lineLinkFailed: {
    th: 'เชื่อมบัญชี LINE ไม่สำเร็จ กรุณาลองใหม่อีกครั้ง',
    en: 'Couldn’t link your LINE account. Please try again.',
  },
  oauthCancelled: {
    th: 'ยกเลิกการเข้าสู่ระบบแล้ว ลองใหม่ได้เลย',
    en: 'Sign-in was cancelled. You can try again.',
  },
  googleExisting: {
    th: 'อีเมลนี้มีบัญชี RAVENTA อยู่แล้ว — เข้าสู่ระบบด้วยวิธีเดิมก่อน (อีเมล/รหัสผ่าน หรือ LINE) แล้วเชื่อม Google ได้ที่ บัญชีของฉัน › ตั้งค่า',
    en: 'This email already has a RAVENTA account — sign in the usual way first (email/password or LINE), then link Google in My account › Settings',
  },
  statusPending: { th: 'รอยืนยันอีเมล', en: 'Awaiting email check' },
  googlePendingHint: {
    th: 'มีการกดเข้าด้วย Google ที่อีเมลนี้ แต่ยังไม่ได้ยืนยันรหัสทางอีเมล — ถ้าเป็นคุณ ออกจากระบบแล้วกด “เข้าสู่ระบบด้วย Google” เพื่อยืนยัน ถ้าไม่ใช่คุณ กดยกเลิกการเชื่อม',
    en: 'Someone signed in with Google on this email but hasn’t confirmed the emailed code — if it was you, sign out and use “Continue with Google” to confirm; if not, unlink it.',
  },
  unlinkButton: { th: 'ยกเลิกการเชื่อม', en: 'Unlink' },
  unlinkAsk: {
    th: 'ยกเลิกการเชื่อม {p}? หลังจากนี้จะเข้าสู่ระบบด้วย {p} ไม่ได้ จนกว่าจะเชื่อมใหม่',
    en: 'Unlink {p}? You won’t be able to sign in with {p} until you link it again.',
  },
  unlinkYes: { th: 'ยืนยันยกเลิก', en: 'Unlink' },
  unlinkNo: { th: 'ไม่ใช่', en: 'Keep it' },
  unlinkDone: { th: 'ยกเลิกการเชื่อมแล้ว', en: 'Unlinked.' },
  unlinkLastMethod: {
    th: 'ยกเลิกไม่ได้ เพราะเป็นวิธีเข้าสู่ระบบเดียวที่เหลือ — ตั้งรหัสผ่านหรือเชื่อมวิธีอื่นก่อน',
    en: 'This is your only way to sign in — set a password or link another method first.',
  },
  unlinkFailed: { th: 'ยกเลิกไม่สำเร็จ กรุณาลองอีกครั้ง', en: 'Couldn’t unlink. Please try again.' },
  googleLinkTitle: { th: 'เชื่อม Google กับบัญชีเดิมของคุณ', en: 'Link Google to your existing account' },
  googleLinkIntro: {
    th: 'อีเมลนี้มีบัญชี RAVENTA อยู่แล้ว เพื่อความปลอดภัยเราจะส่งรหัส 6 หลักไปที่อีเมลของบัญชี ยืนยันแล้วจะเข้าสู่ระบบและเชื่อม Google ให้ทันที',
    en: 'This email already has a RAVENTA account. For your security we’ll email a 6-digit code to it — once confirmed you’re signed in and Google is linked.',
  },
  googleLinkSend: { th: 'ส่งรหัสไปที่', en: 'Send a code to' },
  googleLinkConfirm: { th: 'ยืนยันและเชื่อม Google', en: 'Confirm and link Google' },
  googleLinkLinking: { th: 'เชื่อม Google แล้ว กำลังเข้าสู่ระบบ…', en: 'Google linked — signing you in…' },
  googleLinkNoInbox: {
    th: 'เข้าอีเมลนี้ไม่ได้แล้ว? ติดต่อเคาน์เตอร์พร้อมบัตรประชาชน ทีมงานจะช่วยเปลี่ยนอีเมลให้',
    en: 'Can’t get into this email any more? Visit the counter with photo ID and we’ll change it for you.',
  },
  oauthFailed: {
    th: 'เข้าสู่ระบบไม่สำเร็จ กรุณาลองใหม่อีกครั้ง หากยังไม่ได้ กรุณาติดต่อเรา',
    en: 'Sign-in didn’t work. Please try again, or contact us if it keeps happening.',
  },
  signupSuccess: {
    th: 'สมัครสำเร็จ! กรุณาตรวจสอบอีเมลเพื่อยืนยันบัญชีก่อนเข้าสู่ระบบ',
    en: 'Success! Please check your email to confirm your account before logging in.',
  },
  accountHeading: { th: 'บัญชีของฉัน', en: 'My Account' },
  memberNoFieldLabel: { th: 'หมายเลขสมาชิก', en: 'Member No.' },
  memberSince: { th: 'สมาชิกตั้งแต่', en: 'Member since' },
  joinedFieldLabel: { th: 'วันที่สมัคร', en: 'Joined' },
  myPackages: { th: 'แพ็กเกจของฉัน', en: 'My packages' },
  myGifts: { th: 'ของขวัญของฉัน', en: 'My gifts' },
  myGiftsHint: { th: 'ยื่นบัตรสมาชิกที่เคาน์เตอร์ได้เลย — พนักงานจะใช้สิทธิ์ของขวัญให้อัตโนมัติ', en: 'Just show your member card at the counter — the gift is used automatically' },
  historyLink: { th: 'ประวัติการใช้บริการ', en: 'My visits' },
  settingsLink: { th: 'ข้อมูลส่วนตัวและการตั้งค่า', en: 'Personal details & settings' },
  settingsHeading: { th: 'ข้อมูลส่วนตัวและการตั้งค่า', en: 'Personal Details & Settings' },
  backToAccount: { th: 'บัญชีของฉัน', en: 'My Account' },
  loginMethodsHeading: { th: 'ช่องทางเข้าสู่ระบบ', en: 'Sign-in Methods' },
  loginMethodEmail: { th: 'อีเมลและรหัสผ่าน', en: 'Email & password' },
  loginMethodGoogle: { th: 'Google', en: 'Google' },
  loginMethodLine: { th: 'LINE', en: 'LINE' },
  statusInUse: { th: 'ใช้อยู่', en: 'In use' },
  statusNotSet: { th: 'ไม่ได้ตั้งไว้', en: 'Not set up' },
  statusLinked: { th: 'เชื่อมแล้ว', en: 'Linked' },
  statusNotLinked: { th: 'ไม่ได้เชื่อม', en: 'Not linked' },
  lineLinkShort: { th: 'เชื่อม LINE', en: 'Link LINE' },
  googleLinkShort: { th: 'เชื่อม Google', en: 'Link Google' },
  googleLinkedSuccess: { th: 'เชื่อมบัญชี Google เรียบร้อยแล้ว', en: 'Your Google account is now linked.' },
  googleLinkAlreadyUsed: {
    th: 'บัญชี Google นี้ถูกใช้สมัครสมาชิกอีกบัญชีหนึ่งอยู่แล้ว กรุณาติดต่อเราเพื่อรวมบัญชี',
    en: 'This Google account is already used by another membership. Please contact us to merge them.',
  },
  googleLinkFailed: { th: 'เชื่อมบัญชี Google ไม่สำเร็จ กรุณาลองใหม่อีกครั้ง', en: 'Couldn’t link your Google account. Please try again.' },
  googleOpenInBrowser: {
    th: 'เปิดหน้านี้ใน Safari หรือ Chrome เพื่อเชื่อม Google (Google ไม่รองรับในแอป LINE)',
    en: 'Open this page in Safari or Chrome to link Google (not supported inside the LINE app).',
  },
  emailSetupButton: { th: 'ตั้งค่า', en: 'Set up' },
  passwordSetupButton: { th: 'ตั้งรหัสผ่าน', en: 'Set password' },
  emailUnverified: { th: 'ยังไม่ยืนยัน', en: 'Not verified' },
  verifyEmailLink: { th: 'ยืนยันอีเมล', en: 'Verify email' },
  emailSetupIntro: {
    th: 'ยืนยันอีเมลของคุณ แล้วตั้งรหัสผ่าน เพื่อเข้าสู่ระบบด้วยอีเมลได้อีกทาง บัตรสมาชิกและแต้มยังเป็นบัญชีเดิม',
    en: 'Verify your email and set a password to also sign in with email. Your card and stamps stay on this account.',
  },
  passwordSetupIntroBefore: { th: 'ตั้งรหัสผ่าน แล้วครั้งต่อไปเข้าสู่ระบบด้วย', en: 'Set a password, then next time sign in with' },
  passwordSetupIntroAfter: { th: 'และรหัสผ่านนี้ได้เลย', en: 'and this password.' },
  sendCodeButton: { th: 'ส่งรหัสยืนยัน', en: 'Send code' },
  emailCodeSentTo: { th: 'ส่งรหัส 6 หลักไปที่', en: 'We sent a 6-digit code to' },
  emailCodeCheckSpam: {
    th: 'ไม่เห็นอีเมล? ดูในโฟลเดอร์ Junk / สแปม หรือโปรโมชัน · ถ้ากล่องอีเมลเต็มจะรับไม่ได้ ลบอีเมลเก่าให้มีที่ว่างแล้วขอส่งใหม่',
    en: 'Can’t see it? Check your Junk/spam or promotions folder. A full inbox can’t receive it — free up space, then ask for a new one.',
  },
  emailCodeLabel: { th: 'รหัสยืนยัน', en: 'Verification code' },
  emailCodeConfirm: { th: 'ยืนยันอีเมล', en: 'Verify email' },
  emailCodeResend: { th: 'ส่งรหัสใหม่', en: 'Send a new code' },
  emailCodeResent: { th: 'ส่งรหัสใหม่แล้ว', en: 'A new code is on its way.' },
  emailCodeChangeEmail: { th: 'แก้อีเมล', en: 'Change email' },
  emailVerifiedDone: { th: 'ยืนยันอีเมลแล้ว', en: 'Email verified' },
  setPasswordButton: { th: 'บันทึกรหัสผ่าน', en: 'Save password' },
  skipForNow: { th: 'ไว้ทีหลัง', en: 'Not now' },
  emailLoginReady: {
    th: 'เรียบร้อย ครั้งต่อไปเข้าสู่ระบบด้วยอีเมลและรหัสผ่านนี้ได้เลย',
    en: 'All set — you can now sign in with this email and password.',
  },
  profilePhotoHeading: { th: 'รูปโปรไฟล์', en: 'Profile Photo' },
  personalInfoHeading: { th: 'ข้อมูลส่วนตัว', en: 'Personal Details' },
  adminLinkLabel: { th: 'หน้าแอดมิน', en: 'Admin dashboard' },
  nameFieldLabel: { th: 'ชื่อ-นามสกุล', en: 'Name' },
  phoneFieldLabel: { th: 'เบอร์โทรศัพท์', en: 'Phone Number' },
  provinceFieldLabel: { th: 'จังหวัด', en: 'Province' },
  nationalityFieldLabel: { th: 'สัญชาติ', en: 'Nationality' },
  emailFieldLabel: { th: 'อีเมล', en: 'Email' },
  roleFieldLabel: { th: 'สถานะบัญชี', en: 'Account Type' },
  // Admins are members too (own card, own visits) — the label says both.
  roleAdmin: { th: 'สมาชิก · แอดมิน', en: 'Member · Admin' },
  roleCustomer: { th: 'สมาชิก', en: 'Member' },
  roleStaff: { th: 'สมาชิก · พนักงาน', en: 'Member · Staff' },
  deskLinkLabel: { th: 'หน้าเช็คอินหน้าร้าน', en: 'Front desk check-in' },
  stampCardHeading: { th: 'บัตรสะสม', en: 'Stamp card' },
  stampCardHint: { th: 'มาครบ 10 ครั้ง รับ Day Pass วันธรรมดาฟรี 1 ครั้ง', en: 'Visit 10 times, get a free weekday Day Pass' },
  stampCardReward: { th: 'คุณมีสิทธิ์ Day Pass ฟรี — แจ้งพนักงานตอนเช็คอิน', en: 'You have a free Day Pass — tell staff when you check in' },
  goToAdmin: { th: 'ไปที่หน้าแอดมิน →', en: 'Go to admin dashboard →' },
  signOutButton: { th: 'ออกจากระบบ', en: 'Sign Out' },
  adminHeading: { th: 'แดชบอร์ดแอดมิน', en: 'Admin Dashboard' },
  adminWelcome: { th: 'ยินดีต้อนรับ', en: 'Welcome' },
  adminPlaceholder: {
    th: 'พื้นที่นี้สำหรับทีมงาน RAVENTA — เตรียมไว้สำหรับจัดการเนื้อหาและข้อมูลลูกค้าในขั้นถัดไป',
    en: 'This area is for the RAVENTA team — content and customer management tools will go here next.',
  },
  backHome: { th: '← กลับหน้าหลัก', en: '← Back to homepage' },
  completeProfileHeading: { th: 'กรอกข้อมูลให้ครบก่อนใช้งาน', en: 'Complete Your Profile' },
  completeProfileSub: {
    th: 'กรุณากรอกข้อมูลให้ครบก่อนใช้งานบัญชี',
    en: 'Please complete the information below before using your account.',
  },
  saveButton: { th: 'บันทึกและดำเนินการต่อ', en: 'Save and Continue' },
  forgotPasswordLink: { th: 'ลืมรหัสผ่าน?', en: 'Forgot password?' },
  forgotPasswordHeading: { th: 'ลืมรหัสผ่าน', en: 'Forgot Password' },
  forgotPasswordSub: {
    th: 'กรอกอีเมลที่ใช้สมัคร แล้วเราจะส่งลิงก์สำหรับตั้งรหัสผ่านใหม่ไปให้',
    en: "Enter the email you signed up with and we'll send a link to reset your password.",
  },
  forgotPasswordButton: { th: 'ส่งลิงก์รีเซ็ตรหัสผ่าน', en: 'Send Reset Link' },
  forgotPasswordSuccess: {
    th: 'ถ้าอีเมลนี้มีอยู่ในระบบ เราได้ส่งลิงก์สำหรับตั้งรหัสผ่านใหม่ไปให้แล้ว กรุณาตรวจสอบกล่องจดหมาย',
    en: 'If that email is in our system, a password reset link is on its way — please check your inbox.',
  },
  backToLogin: { th: '← กลับไปเข้าสู่ระบบ', en: '← Back to log in' },
  resetPasswordHeading: { th: 'ตั้งรหัสผ่านใหม่', en: 'Set New Password' },
  resetPasswordSub: { th: 'กรอกรหัสผ่านใหม่ที่ต้องการใช้', en: 'Enter the new password you want to use.' },
  newPasswordLabel: { th: 'รหัสผ่านใหม่', en: 'New Password' },
  resetPasswordButton: { th: 'บันทึกรหัสผ่านใหม่', en: 'Save New Password' },
  changePasswordLink: { th: 'เปลี่ยนรหัสผ่าน', en: 'Change Password' },
  acceptPrivacyBefore: { th: 'ฉันได้อ่านและยอมรับ', en: 'I have read and agree to the' },
  acceptPrivacyPolicyLink: { th: 'นโยบายความเป็นส่วนตัว', en: 'Privacy Policy' },
  acceptPrivacyAnd: { th: 'และ', en: 'and' },
  acceptPrivacyTermsLink: { th: 'ข้อกำหนดการใช้งาน', en: 'Terms of Service' },
  acceptPrivacyRequired: {
    th: 'กรุณายอมรับนโยบายความเป็นส่วนตัวและข้อกำหนดการใช้งานก่อนสมัครสมาชิก',
    en: 'Please accept the Privacy Policy and Terms of Service before creating an account.',
  },
  oauthConsentNote: {
    th: 'การดำเนินการต่อถือว่าคุณยอมรับนโยบายความเป็นส่วนตัวและข้อกำหนดการใช้งานของเรา',
    en: 'By continuing, you agree to our Privacy Policy and Terms of Service.',
  },
  editButton: { th: 'แก้ไข', en: 'Edit' },
  cancelButton: { th: 'ยกเลิก', en: 'Cancel' },
  adminMembersHeading: { th: 'รายชื่อสมาชิก', en: 'Members' },
  adminSearchPlaceholder: { th: 'ค้นหาชื่อ, เบอร์โทร, อีเมล หรือหมายเลขสมาชิก', en: 'Search name, phone, email, or member no.' },
  adminNoMembersFound: { th: 'ไม่พบสมาชิกที่ค้นหา', en: 'No members match your search.' },
  adminBackToMembers: { th: '← กลับไปรายชื่อสมาชิก', en: '← Back to members' },
  adminEditMemberHeading: { th: 'แก้ไขข้อมูลสมาชิก', en: 'Edit Member' },
}
