type Bilingual = { th: string; en: string }

export const authCopy: Record<string, Bilingual> = {
  loginHeading: { th: 'เข้าสู่ระบบ', en: 'Log In' },
  signupHeading: { th: 'สมัครสมาชิก', en: 'Sign Up' },
  firstNameLabel: { th: 'ชื่อ', en: 'First Name' },
  lastNameLabel: { th: 'นามสกุล', en: 'Last Name' },
  phoneLabel: { th: 'เบอร์โทรศัพท์', en: 'Phone Number' },
  provinceLabel: { th: 'จังหวัดที่อยู่อาศัย', en: 'Province of Residence' },
  provincePlaceholder: { th: 'เลือกจังหวัด', en: 'Select a province' },
  nationalityLabel: { th: 'สัญชาติ', en: 'Nationality' },
  nationalityPlaceholder: { th: 'เลือกสัญชาติ', en: 'Select nationality' },
  emailLabel: { th: 'อีเมล', en: 'Email' },
  passwordLabel: { th: 'รหัสผ่าน', en: 'Password' },
  confirmPasswordLabel: { th: 'ยืนยันรหัสผ่าน', en: 'Confirm Password' },
  passwordHint: {
    th: 'อย่างน้อย 8 ตัวอักษร มีทั้งตัวอักษรและตัวเลข',
    en: 'At least 8 characters, with both letters and numbers',
  },
  passwordMismatch: { th: 'รหัสผ่านทั้งสองช่องไม่ตรงกัน', en: 'Passwords do not match' },
  loginButton: { th: 'เข้าสู่ระบบ', en: 'Log In' },
  signupButton: { th: 'สมัครสมาชิก', en: 'Create Account' },
  orContinueWith: { th: 'หรือดำเนินการต่อด้วย', en: 'Or continue with' },
  google: { th: 'ดำเนินการต่อด้วย Google', en: 'Continue with Google' },
  line: { th: 'ดำเนินการต่อด้วย LINE', en: 'Continue with LINE' },
  lineConnecting: { th: 'กำลังเข้าสู่ระบบด้วย LINE…', en: 'Signing you in with LINE…' },
  otherSignInOptions: { th: 'เข้าสู่ระบบด้วยวิธีอื่น', en: 'Other ways to sign in' },
  avatarChange: { th: 'เปลี่ยนรูปโปรไฟล์', en: 'Change photo' },
  avatarRemove: { th: 'ลบรูปที่อัปโหลด', en: 'Remove uploaded photo' },
  avatarBadFile: {
    th: 'เปิดไฟล์รูปนี้ไม่ได้ กรุณาเลือกรูป JPG หรือ PNG',
    en: 'That file couldn’t be opened. Please choose a JPG or PNG photo.',
  },
  avatarUploadFailed: { th: 'อัปโหลดรูปไม่สำเร็จ กรุณาลองใหม่อีกครั้ง', en: 'Upload failed. Please try again.' },
  mergeTitle: { th: 'อีเมลนี้เป็นสมาชิก RAVENTA อยู่แล้ว', en: 'This email is already a RAVENTA member' },
  mergeBody: {
    th: 'ต้องการเชื่อม LINE นี้เข้ากับบัญชีเดิมไหม เลขสมาชิกและข้อมูลเดิมจะยังอยู่ครบ',
    en: 'Link this LINE account to that membership? Your member number and details stay the same.',
  },
  mergeLinkButton: { th: 'เชื่อมกับบัญชีเดิม', en: 'Link to my existing account' },
  mergeTitlePhone: { th: 'เบอร์นี้เป็นสมาชิก RAVENTA อยู่แล้ว', en: 'This phone number is already a RAVENTA member' },
  mergeUseAnotherPhone: { th: 'ใช้เบอร์อื่น (สมัครเป็นสมาชิกใหม่)', en: 'Use another number (new membership)' },
  mergeTargetLimit: {
    th: 'มีการขอรหัสสำหรับบัญชีนี้หลายครั้งเกินไปวันนี้ กรุณาลองใหม่พรุ่งนี้ หรือติดต่อเรา',
    en: 'Too many code requests for this membership today. Please try again tomorrow or contact us.',
  },
  mergeUseAnother: { th: 'ใช้อีเมลอื่น (สมัครเป็นสมาชิกใหม่)', en: 'Use another email (new membership)' },
  mergeCodeSent: { th: 'ส่งรหัส 6 หลักไปที่', en: 'We sent a 6-digit code to' },
  mergeCodeLabel: { th: 'รหัสยืนยัน', en: 'Verification code' },
  mergeVerifyButton: { th: 'ยืนยัน', en: 'Verify' },
  mergeResend: { th: 'ส่งรหัสอีกครั้ง', en: 'Send a new code' },
  mergeLinking: { th: 'กำลังเชื่อม LINE เข้ากับบัญชีของคุณ…', en: 'Linking LINE to your account…' },
  mergeWrongCode: { th: 'รหัสไม่ถูกต้อง กรุณาลองอีกครั้ง', en: 'That code isn’t right. Please try again.' },
  mergeExpired: { th: 'รหัสหมดอายุแล้ว กรุณากดส่งรหัสอีกครั้ง', en: 'That code has expired. Please send a new one.' },
  mergeTooMany: {
    th: 'กรอกรหัสผิดหลายครั้งเกินไป กรุณากดส่งรหัสใหม่',
    en: 'Too many wrong attempts. Please send a new code.',
  },
  mergeTooSoon: { th: 'เพิ่งส่งรหัสไป กรุณารอสักครู่แล้วลองใหม่', en: 'A code was just sent. Please wait a minute.' },
  mergeTargetHasLine: {
    th: 'บัญชีเดิมนี้เชื่อมกับ LINE อีกบัญชีไว้แล้ว กรุณาติดต่อเรา',
    en: 'That membership is already linked to a different LINE account. Please contact us.',
  },
  mergeNotFound: {
    th: 'เชื่อมกับบัญชีนี้จากที่นี่ไม่ได้ กรุณาติดต่อเรา หรือใช้อีเมลอื่น',
    en: 'We can’t link that membership from here. Please contact us or use another email.',
  },
  mergeFailed: {
    th: 'เกิดข้อผิดพลาด กรุณาลองใหม่อีกครั้ง หากยังไม่ได้ กรุณาติดต่อเรา',
    en: 'Something went wrong. Please try again, or contact us if it keeps happening.',
  },
  emailWhyHint: {
    th: 'ใช้ส่งเลขสมาชิกและข่าวสารสำคัญเกี่ยวกับบัญชีของคุณ',
    en: 'We’ll send your member number and important account updates here.',
  },
  lineLinkLabel: { th: 'บัญชี LINE', en: 'LINE Account' },
  lineLinkHint: {
    th: 'เชื่อม LINE ไว้ แล้วครั้งต่อไปกดเข้าสู่ระบบด้วย LINE ได้เลย และรับข่าวสารสมาชิกทาง LINE',
    en: 'Link LINE to sign in with it next time and get member updates on LINE.',
  },
  lineLinkButton: { th: 'เชื่อมบัญชี LINE', en: 'Link LINE Account' },
  lineLinked: { th: 'เชื่อมกับ LINE แล้ว', en: 'Linked to LINE' },
  lineLinkedSuccess: { th: 'เชื่อมบัญชี LINE เรียบร้อยแล้ว', en: 'Your LINE account is now linked.' },
  lineLinkAlreadyUsed: {
    th: 'บัญชี LINE นี้ถูกใช้สมัครสมาชิกอีกบัญชีหนึ่งอยู่แล้ว กรุณาติดต่อเราเพื่อรวมบัญชี',
    en: 'This LINE account is already used by another membership. Please contact us to merge them.',
  },
  lineLinkFailed: {
    th: 'เชื่อมบัญชี LINE ไม่สำเร็จ กรุณาลองใหม่อีกครั้ง',
    en: 'Couldn’t link your LINE account. Please try again.',
  },
  oauthCancelled: {
    th: 'ยกเลิกการเข้าสู่ระบบแล้ว ลองใหม่ได้เลย',
    en: 'Sign-in was cancelled. You can try again.',
  },
  oauthFailed: {
    th: 'เข้าสู่ระบบไม่สำเร็จ กรุณาลองใหม่อีกครั้ง หากยังไม่ได้ กรุณาติดต่อเรา',
    en: 'Sign-in didn’t work. Please try again, or contact us if it keeps happening.',
  },
  signupSuccess: {
    th: 'สมัครสำเร็จ! กรุณาตรวจสอบอีเมลเพื่อยืนยันบัญชีก่อนเข้าสู่ระบบ',
    en: 'Success! Please check your email to confirm your account before logging in.',
  },
  accountHeading: { th: 'บัญชีของฉัน', en: 'My Account' },
  memberNoFieldLabel: { th: 'หมายเลขสมาชิก', en: 'Member No.' },
  nameFieldLabel: { th: 'ชื่อ-นามสกุล', en: 'Name' },
  phoneFieldLabel: { th: 'เบอร์โทรศัพท์', en: 'Phone Number' },
  provinceFieldLabel: { th: 'จังหวัด', en: 'Province' },
  nationalityFieldLabel: { th: 'สัญชาติ', en: 'Nationality' },
  emailFieldLabel: { th: 'อีเมล', en: 'Email' },
  roleFieldLabel: { th: 'สถานะบัญชี', en: 'Account Type' },
  roleAdmin: { th: 'แอดมิน', en: 'Admin' },
  roleCustomer: { th: 'สมาชิก', en: 'Member' },
  goToAdmin: { th: 'ไปที่หน้าแอดมิน →', en: 'Go to admin dashboard →' },
  signOutButton: { th: 'ออกจากระบบ', en: 'Sign Out' },
  adminHeading: { th: 'แดชบอร์ดแอดมิน', en: 'Admin Dashboard' },
  adminWelcome: { th: 'ยินดีต้อนรับ', en: 'Welcome' },
  adminPlaceholder: {
    th: 'พื้นที่นี้สำหรับทีมงาน RAVENTA — เตรียมไว้สำหรับจัดการเนื้อหาและข้อมูลลูกค้าในขั้นถัดไป',
    en: 'This area is for the RAVENTA team — content and customer management tools will go here next.',
  },
  backHome: { th: '← กลับหน้าหลัก', en: '← Back to homepage' },
  completeProfileHeading: { th: 'กรอกข้อมูลให้ครบก่อนใช้งาน', en: 'Complete Your Profile' },
  completeProfileSub: {
    th: 'กรุณากรอกข้อมูลให้ครบก่อนใช้งานบัญชี',
    en: 'Please complete the information below before using your account.',
  },
  saveButton: { th: 'บันทึกและดำเนินการต่อ', en: 'Save and Continue' },
  forgotPasswordLink: { th: 'ลืมรหัสผ่าน?', en: 'Forgot password?' },
  forgotPasswordHeading: { th: 'ลืมรหัสผ่าน', en: 'Forgot Password' },
  forgotPasswordSub: {
    th: 'กรอกอีเมลที่ใช้สมัคร แล้วเราจะส่งลิงก์สำหรับตั้งรหัสผ่านใหม่ไปให้',
    en: "Enter the email you signed up with and we'll send a link to reset your password.",
  },
  forgotPasswordButton: { th: 'ส่งลิงก์รีเซ็ตรหัสผ่าน', en: 'Send Reset Link' },
  forgotPasswordSuccess: {
    th: 'ถ้าอีเมลนี้มีอยู่ในระบบ เราได้ส่งลิงก์สำหรับตั้งรหัสผ่านใหม่ไปให้แล้ว กรุณาตรวจสอบกล่องจดหมาย',
    en: 'If that email is in our system, a password reset link is on its way — please check your inbox.',
  },
  backToLogin: { th: '← กลับไปเข้าสู่ระบบ', en: '← Back to log in' },
  resetPasswordHeading: { th: 'ตั้งรหัสผ่านใหม่', en: 'Set New Password' },
  resetPasswordSub: { th: 'กรอกรหัสผ่านใหม่ที่ต้องการใช้', en: 'Enter the new password you want to use.' },
  newPasswordLabel: { th: 'รหัสผ่านใหม่', en: 'New Password' },
  resetPasswordButton: { th: 'บันทึกรหัสผ่านใหม่', en: 'Save New Password' },
  changePasswordLink: { th: 'เปลี่ยนรหัสผ่าน', en: 'Change Password' },
  acceptPrivacyBefore: { th: 'ฉันได้อ่านและยอมรับ', en: 'I have read and agree to the' },
  acceptPrivacyPolicyLink: { th: 'นโยบายความเป็นส่วนตัว', en: 'Privacy Policy' },
  acceptPrivacyAnd: { th: 'และ', en: 'and' },
  acceptPrivacyTermsLink: { th: 'ข้อกำหนดการใช้งาน', en: 'Terms of Service' },
  acceptPrivacyRequired: {
    th: 'กรุณายอมรับนโยบายความเป็นส่วนตัวและข้อกำหนดการใช้งานก่อนสมัครสมาชิก',
    en: 'Please accept the Privacy Policy and Terms of Service before creating an account.',
  },
  oauthConsentNote: {
    th: 'การดำเนินการต่อถือว่าคุณยอมรับนโยบายความเป็นส่วนตัวและข้อกำหนดการใช้งานของเรา',
    en: 'By continuing, you agree to our Privacy Policy and Terms of Service.',
  },
  editButton: { th: 'แก้ไข', en: 'Edit' },
  cancelButton: { th: 'ยกเลิก', en: 'Cancel' },
  adminMembersHeading: { th: 'รายชื่อสมาชิก', en: 'Members' },
  adminSearchPlaceholder: { th: 'ค้นหาชื่อ, เบอร์โทร, อีเมล หรือหมายเลขสมาชิก', en: 'Search name, phone, email, or member no.' },
  adminNoMembersFound: { th: 'ไม่พบสมาชิกที่ค้นหา', en: 'No members match your search.' },
  adminBackToMembers: { th: '← กลับไปรายชื่อสมาชิก', en: '← Back to members' },
  adminEditMemberHeading: { th: 'แก้ไขข้อมูลสมาชิก', en: 'Edit Member' },
}
